$
$ANSA_VERSION;20.1.0;
$
$
$ file created by  A N S A  Mon Aug  3 16:40:02 2020
$
$ output from :
$
$ C:/Meshing_WorkingFolder/VIVA-Plus/vivaplus-50F_v0-1-6.ansa
$
$ANSA_USER_ATTRIBUTES;vivaplus-20-Neck.key;INCLUDE;DM/IO Index;TEXT;5;DM/Status;
$TEXT;WIP;
$
$
$
$
$
$
$ANSA_COLOR;vivaplus-20-Neck.key;INCLUDE;.603921592235565;0.52549022436142;.1686
$27455830574;1.;
*KEYWORD
*PART
NE_Hyoid
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200101    200101    200101                             0         0          
*SECTION_SHELL_TITLE
NE_Hyoid
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200101         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
NE-ligament-OC-C1-AAOM-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200510    200510    203009                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-AAOM-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200510         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.9       0.9       0.9       0.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Apical-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200520    200520    203014                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Apical-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200520         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Cruciform-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200530    200530    203013                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Cruciform-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200530         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Tectoria-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200540    200540    203015                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Tectoria-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200540         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       2.5       2.5       2.5       2.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Alar-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200550    200550    213019                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Alar-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200550         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       2.9       2.9       2.9       2.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-AOCJ-CL-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200560    200560    213014                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-AOCJ-CL-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200560         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-PAOM-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200570    200570    203008                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-PAOM-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200570         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.9       0.9       0.9       0.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Transverse-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200580    200580    203016                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Transverse-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200580         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE_L_Stylohyoid_Ligament
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    200610    200610    214001                             0                    
*SECTION_BEAM_TITLE
NE_L_Stylohyoid_Ligament
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    200610         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
    317.16        0.                  4.        0.        0.        0.        0.
*PART
NE-ligament-C1-C2-ALL-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200710    200710    203011                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-ALL-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200710         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-AAAM-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200720    200720    203012                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-AAAM-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200720         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.9       0.9       0.9       0.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-CL-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200730    200730    213015                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-CL-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200730         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-IL-Cruciform-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200740    200740    203018                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-IL-Cruciform-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200740         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-Transverse-Center-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200750    200750    203019                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-Transverse-Center-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200750         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-PAAM-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200760    200760    203017                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-PAAM-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200760         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.9       0.9       0.9       0.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-Vertebra-C1-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201011    201011    200011                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.5        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C1-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201011         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.46      0.46      0.46      0.46        0.                  0.          
*PART
NE-Vertebra-C1-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201012    201012    200012                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C1-Trabecular-M
$    SECID|   ELFORM|
    201012        13
*PART_CONTACT
NE-Vertebra-C2-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201021    201021    200021                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.5        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C2-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201021         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.46      0.46      0.46      0.46        0.                  0.          
*PART
NE-Vertebra-C2-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201022    201022    200022                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C2-Trabecular-M
$    SECID|   ELFORM|
    201022        13
*PART
NE-Vertebra-C2-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201025    201025    200024                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C2-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201025         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.58      0.58      0.58      0.58        0.                  0.          
*PART
NE-Vertebra-C2-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201026    201026    203020                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C2-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201026         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C3-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201031    201031    200031                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.5        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201031         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.46      0.46      0.46      0.46        0.                  0.          
*PART
NE-Vertebra-C3-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201032    201032    200032                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C3-Trabecular-M
$    SECID|   ELFORM|
    201032        13
*PART
NE-Vertebra-C3-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201033    201033    200023                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201033         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.63      0.63      0.63      0.63        0.                  0.          
*PART
NE-Vertebra-C3-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201034    201034    203029                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201034         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C3-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201035    201035    200034                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201035         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.58      0.58      0.58      0.58        0.                  0.          
*PART
NE-Vertebra-C3-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201036    201036    203030                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201036         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C4-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201041    201041    200041                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.5        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201041         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.48      0.48      0.48      0.48        0.                  0.          
*PART
NE-Vertebra-C4-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201042    201042    200042                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C4-Trabecular-M
$    SECID|   ELFORM|
    201042        13
*PART
NE-Vertebra-C4-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201043    201043    200033                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201043         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.62      0.62      0.62      0.62        0.                  0.          
*PART
NE-Vertebra-C4-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201044    201044    203039                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201044         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C4-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201045    201045    200044                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201045         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.56      0.56      0.56      0.56        0.                  0.          
*PART
NE-Vertebra-C4-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201046    201046    203040                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201046         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C5-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201051    201051    200051                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.3        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201051         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
NE-Vertebra-C5-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201052    201052    200052                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C5-Trabecular-M
$    SECID|   ELFORM|
    201052        13
*PART
NE-Vertebra-C5-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201053    201053    200043                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201053         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.55      0.55      0.55      0.55        0.                  0.          
*PART
NE-Vertebra-C5-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201054    201054    203049                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201054         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C5-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201055    201055    200054                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201055         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.62      0.62      0.62      0.62        0.                  0.          
*PART
NE-Vertebra-C5-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201056    201056    203050                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201056         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C6-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201061    201061    200061                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.4        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201061         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.58      0.58      0.58      0.58        0.                  0.          
*PART
NE-Vertebra-C6-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201062    201062    200062                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C6-Trabecular-M
$    SECID|   ELFORM|
    201062        13
*PART
NE-Vertebra-C6-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201063    201063    200053                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201063         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.63      0.63      0.63      0.63        0.                  0.          
*PART
NE-Vertebra-C6-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201064    201064    203059                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201064         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C6-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201065    201065    200064                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201065         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.65      0.65      0.65      0.65        0.                  0.          
*PART
NE-Vertebra-C6-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201066    201066    203060                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201066         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C7-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201071    201071    200071                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.4        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201071         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.59      0.59      0.59      0.59        0.                  0.          
*PART
NE-Vertebra-C7-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201072    201072    200072                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C7-Trabecular-M
$    SECID|   ELFORM|
    201072        13
*PART
NE-Vertebra-C7-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201073    201073    200063                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201073         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.6       0.6       0.6       0.6        0.                  0.          
*PART
NE-Vertebra-C7-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201074    201074    203069                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201074         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C7-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201075    201075    200074                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201075         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.67      0.67      0.67      0.67        0.                  0.          
*PART
NE-Vertebra-C7-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201076    201076    203070                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201076         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-Articular-Process-OC-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201104    201104    213011                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-OC-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201104         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C1-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201111    201111    213013             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C1-Superior-Cartilage-L
$    SECID|   ELFORM|
    201111         1
*PART
NE-Vertebra-Articular-Process-C1-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201112    201112    213012                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C1-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201112         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C1-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201113    201113    213016             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C1-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201113         1
*PART
NE-Vertebra-Articular-Process-C1-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201114    201114    213017                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C1-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201114         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C2-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201121    201121    213010             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C2-Superior-Cartilage-L
$    SECID|   ELFORM|
    201121         1
*PART
NE-Vertebra-Articular-Process-C2-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201122    201122    213018                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C2-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201122         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C2-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201123    201123    213022             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C2-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201123         1
*PART
NE-Vertebra-Articular-Process-C2-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201124    201124    213024                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C2-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201124         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C3-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201131    201131    213023             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C3-Superior-Cartilage-L
$    SECID|   ELFORM|
    201131         1
*PART
NE-Vertebra-Articular-Process-C3-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201132    201132    213025                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C3-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201132         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C3-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201133    201133    213032             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C3-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201133         1
*PART
NE-Vertebra-Articular-Process-C3-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201134    201134    213034                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C3-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201134         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C4-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201141    201141    213033             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C4-Superior-Cartilage-L
$    SECID|   ELFORM|
    201141         1
*PART
NE-Vertebra-Articular-Process-C4-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201142    201142    213035                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C4-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201142         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C4-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201143    201143    213042             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C4-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201143         1
*PART
NE-Vertebra-Articular-Process-C4-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201144    201144    213044                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C4-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201144         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C5-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201151    201151    213043             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C5-Superior-Cartilage-L
$    SECID|   ELFORM|
    201151         1
*PART
NE-Vertebra-Articular-Process-C5-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201152    201152    213045                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C5-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201152         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C5-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201153    201153    213052             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C5-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201153         1
*PART
NE-Vertebra-Articular-Process-C5-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201154    201154    213054                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C5-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201154         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C6-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201161    201161    213053             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C6-Superior-Cartilage-L
$    SECID|   ELFORM|
    201161         1
*PART
NE-Vertebra-Articular-Process-C6-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201162    201162    213055                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C6-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201162         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C6-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201163    201163    213062             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C6-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201163         1
*PART
NE-Vertebra-Articular-Process-C6-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201164    201164    213064                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C6-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201164         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C7-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201171    201171    213063             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C7-Superior-Cartilage-L
$    SECID|   ELFORM|
    201171         1
*PART
NE-Vertebra-Articular-Process-C7-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201172    201172    213065                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C7-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201172         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C7-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201173    201173    213072             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C7-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201173         1
*PART
NE-Vertebra-Articular-Process-C7-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201174    201174    213074                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C7-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201174         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.06      0.06      0.06      0.06        0.                  0.          
*PART
NE-ligaments-C2-C3-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201521    201521    213028                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201521         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C2-C3-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201522    201522    213027                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201522         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C2-C3-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201523    201523    213021                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201523         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C2-C3-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201524    201524    213026                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201524         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C2-C3-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201525    201525    213029                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201525         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.4       1.4       1.4       1.4        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C3-C4-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201531    201531    213038                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201531         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C3-C4-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201532    201532    213037                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201532         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C3-C4-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201533    201533    213031                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201533         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C3-C4-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201534    201534    213036                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201534         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C3-C4-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201535    201535    213039                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201535         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.4       1.4       1.4       1.4        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C4-C5-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201541    201541    213048                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201541         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C4-C5-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201542    201542    213047                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201542         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C4-C5-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201543    201543    213041                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201543         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C4-C5-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201544    201544    213046                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201544         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C4-C5-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201545    201545    213049                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201545         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.4       1.4       1.4       1.4        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C5-C6-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201551    201551    213058                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201551         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C5-C6-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201552    201552    213057                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201552         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C5-C6-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201553    201553    213051                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201553         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C5-C6-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201554    201554    213056                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201554         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C5-C6-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201555    201555    213059                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201555         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.4       1.4       1.4       1.4        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C6-C7-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201561    201561    213068                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201561         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C6-C7-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201562    201562    213067                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201562         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C6-C7-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201563    201563    213061                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201563         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C6-C7-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201564    201564    213066                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201564         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C6-C7-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201565    201565    213069                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201565         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C7-T1-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201571    201571    213078                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201571         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C7-T1-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201572    201572    213077                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201572         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C7-T1-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201573    201573    213071                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201573         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C7-T1-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201574    201574    213076                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201574         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C7-T1-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201575    201575    213079                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201575         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-C2-C3-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202021    202021    203022            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C2-C3-Annulus-ground-M
$    SECID|   ELFORM|
    202021         1
*PART
NE-IVD-C2-C3-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202022    202022    203021            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C2-C3-Nucleus-M
$    SECID|   ELFORM|
    202022         1
*PART
NE-IVD-C3-C4-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202031    202031    203032            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C3-C4-Annulus-ground-M
$    SECID|   ELFORM|
    202031         1
*PART
NE-IVD-C3-C4-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202032    202032    203031            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C3-C4-Nucleus-M
$    SECID|   ELFORM|
    202032         1
*PART
NE-IVD-C4-C5-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202041    202041    203042            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C4-C5-Annulus-ground-M
$    SECID|   ELFORM|
    202041         1
*PART
NE-IVD-C4-C5-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202042    202042    203041            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C4-C5-Nucleus-M
$    SECID|   ELFORM|
    202042         1
*PART
NE-IVD-C5-C6-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202051    202051    203052            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C5-C6-Annulus-ground-M
$    SECID|   ELFORM|
    202051         1
*PART
NE-IVD-C5-C6-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202052    202052    203051            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C5-C6-Nucleus-M
$    SECID|   ELFORM|
    202052         1
*PART
NE-IVD-C6-C7-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202061    202061    203062            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C6-C7-Annulus-ground-M
$    SECID|   ELFORM|
    202061         1
*PART
NE-IVD-C6-C7-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202062    202062    203061            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C6-C7-Nucleus-M
$    SECID|   ELFORM|
    202062         1
*PART
NE-IVD-C7-T1-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202071    202071    203072            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C7-T1-Annulus-ground-M
$    SECID|   ELFORM|
    202071         1
*PART
NE-IVD-C7-T1-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202072    202072    203071            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C7-T1-Nucleus-M
$    SECID|   ELFORM|
    202072         1
*PART
NE-IVD-Annulus-fiber-C2-C3-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202121    202121    203023                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202121         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202122    202122    203024                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202122         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202123    202123    203025                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202123         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202124    202124    203026                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202124         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202125    202125    203027                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202125         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202126    202126    203028                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202126         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202131    202131    203033                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202131         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202132    202132    203034                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202132         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202133    202133    203035                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202133         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202134    202134    203036                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202134         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202135    202135    203037                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202135         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202136    202136    203038                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202136         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202141    202141    203043                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202141         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202142    202142    203044                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202142         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202143    202143    203045                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202143         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202144    202144    203046                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202144         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202145    202145    203047                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202145         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202146    202146    203048                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202146         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202151    202151    203053                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202151         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202152    202152    203054                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202152         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202153    202153    203055                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202153         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202154    202154    203056                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202154         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202155    202155    203057                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202155         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202156    202156    203058                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202156         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202161    202161    203063                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202161         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202162    202162    203064                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202162         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202163    202163    203065                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202163         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202164    202164    203066                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202164         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202165    202165    203067                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202165         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202166    202166    203068                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202166         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202171    202171    203073                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202171         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202172    202172    203074                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202172         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202173    202173    203075                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202173         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202174    202174    203076                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202174         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202175    202175    203077                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202175         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202176    202176    203078                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202176         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE_Neck_Soft_Tissues
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    203001    203001    203001             2000000         0         0          
*SECTION_SOLID_TITLE
NE_Neck_Soft_Tissues
$    SECID|   ELFORM|
    203001         1
*PART
NE_Skin
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    203002    203002    916001                             0         0          
*SECTION_SHELL_TITLE
NE_Skin
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    203002         9   0.83333        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
NE_Soft_Tissue_Interior
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    203003    203003    203003                             0         0          
*SECTION_SHELL_TITLE
NE_Soft_Tissue_Interior
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    203003         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
NE_Trachea
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    203004    203004    203004                             0         0          
*SECTION_SHELL_TITLE
NE_Trachea
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    203004         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
NE_Larynx
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    203005    203005    203005                             0         0          
*SECTION_SHELL_TITLE
NE_Larynx
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    203005         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
NE_C_Tracheal_Cartilage
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    214002    214002    214002                             0                    
*SECTION_BEAM_TITLE
NE_C_Tracheal_Cartilage
$    SECID|   ELFORM|     SHRF|  QT/IRID|      CST|         |      NSM|
    214002         1   0.83333         2        0.                  0.
$      TS1|      TS2|      TT1|      TT2|    NSLOC|    NTLOC|
        1.        1.        1.        1.        0.        0.
*PART
NE-ligament-OC-C1-AOCJ-CL-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    250560    250560    213014                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-AOCJ-CL-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    250560         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-CL-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    250730    250730    213015                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-CL-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    250730         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-Vertebra-Articular-Process-C1-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251111    251111    213013             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C1-Superior-Cartilage-R
$    SECID|   ELFORM|
    251111         1
*PART
NE-Vertebra-Articular-Process-C1-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251112    251112    213012                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C1-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251112         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C1-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251113    251113    213016             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C1-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251113         1
*PART
NE-Vertebra-Articular-Process-C1-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251114    251114    213017                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C1-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251114         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C2-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251121    251121    213010             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C2-Superior-Cartilage-R
$    SECID|   ELFORM|
    251121         1
*PART
NE-Vertebra-Articular-Process-C2-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251122    251122    213018                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C2-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251122         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C2-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251123    251123    213022             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C2-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251123         1
*PART
NE-Vertebra-Articular-Process-C2-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251124    251124    213024                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C2-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251124         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C3-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251131    251131    213023             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C3-Superior-Cartilage-R
$    SECID|   ELFORM|
    251131         1
*PART
NE-Vertebra-Articular-Process-C3-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251132    251132    213025                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C3-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251132         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C3-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251133    251133    213032             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C3-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251133         1
*PART
NE-Vertebra-Articular-Process-C3-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251134    251134    213034                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C3-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251134         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C4-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251141    251141    213033             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C4-Superior-Cartilage-R
$    SECID|   ELFORM|
    251141         1
*PART
NE-Vertebra-Articular-Process-C4-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251142    251142    213035                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C4-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251142         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C4-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251143    251143    213042             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C4-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251143         1
*PART
NE-Vertebra-Articular-Process-C4-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251144    251144    213044                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C4-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251144         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C5-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251151    251151    213043             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C5-Superior-Cartilage-R
$    SECID|   ELFORM|
    251151         1
*PART
NE-Vertebra-Articular-Process-C5-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251152    251152    213045                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C5-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251152         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C5-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251153    251153    213052             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C5-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251153         1
*PART
NE-Vertebra-Articular-Process-C5-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251154    251154    213054                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C5-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251154         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C6-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251161    251161    213053             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C6-Superior-Cartilage-R
$    SECID|   ELFORM|
    251161         1
*PART
NE-Vertebra-Articular-Process-C6-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251162    251162    213055                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C6-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251162         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C6-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251163    251163    213062             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C6-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251163         1
*PART
NE-Vertebra-Articular-Process-C6-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251164    251164    213064                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C6-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251164         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C7-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251171    251171    213063             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C7-Superior-Cartilage-R
$    SECID|   ELFORM|
    251171         1
*PART
NE-Vertebra-Articular-Process-C7-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251172    251172    213065                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C7-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251172         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C7-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251173    251173    213072             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C7-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251173         1
*PART
NE-Vertebra-Articular-Process-C7-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251174    251174    213074                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C7-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251174         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.06      0.06      0.06      0.06        0.                  0.          
*PART
TX-Spine-T1-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401014    401014    203079                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T1-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401014         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
TX-Vertebra-Articular-Process-T1-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401211    401211    213073             2000000         0         0          
*SECTION_SOLID_TITLE
TX-Vertebra-Articular-Process-T1-Superior-Cartilage-L
$    SECID|   ELFORM|
    401211         1
*PART
TX-Vertebra-Articular-Process-T1-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401212    401212    213075                             0         0          
*SECTION_SHELL_TITLE
TX-Vertebra-Articular-Process-T1-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401212         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.06      0.06      0.06      0.06        0.                  0.          
$ANSA_COLOR;200101;SECTION_SHELL;.823529422283173;.552941203117371;.709803938865
$662;1.;
$ANSA_COLOR;200510;SECTION_SHELL;.811764717102051;.298039227724075;.713725507259
$369;1.;
$ANSA_COLOR;200520;SECTION_SHELL;.792156875133514;.984313726425171;.258823543787
$003;1.;
$ANSA_COLOR;200530;SECTION_SHELL;.772549033164978;0.24705882370472;.423529416322
$708;1.;
$ANSA_COLOR;200540;SECTION_SHELL;.807843148708344;.717647075653076;.098039217293
$262;1.;
$ANSA_COLOR;200550;SECTION_SHELL;.800000011920929;.850980401039124;.180392161011
$696;1.;
$ANSA_COLOR;200560;SECTION_SHELL;.658823549747467;.976470589637756;.474509805440
$903;1.;
$ANSA_COLOR;200570;SECTION_SHELL;.984313726425171;.639215707778931;.094117648899
$555;1.;
$ANSA_COLOR;200580;SECTION_SHELL;.764705896377563;.380392163991928;.501960813999
$176;1.;
$ANSA_COLOR;200610;SECTION_BEAM_ELFORM_6;.843137264251709;.184313729405403;.7725
$49033164978;1.;
$ANSA_COLOR;200710;SECTION_SHELL;.819607853889465;.164705887436867;.635294139385
$223;1.;
$ANSA_COLOR;200720;SECTION_SHELL;.756862759590149;.513725519180298;.584313750267
$029;1.;
$ANSA_COLOR;200730;SECTION_SHELL;.670588254928589;.843137264251709;.396078437566
$757;1.;
$ANSA_COLOR;200740;SECTION_SHELL;.780392169952393;.113725490868092;.341176480054
$855;1.;
$ANSA_COLOR;200750;SECTION_SHELL;.815686285495758;.584313750267029;.015686275437
$474;1.;
$ANSA_COLOR;200760;SECTION_SHELL;.996078431606293;.505882382392883;.015686275437
$474;1.;
$ANSA_COLOR;201011;SECTION_SHELL;.760784327983856;.482352942228317;.278431385755
$539;1.;
$ANSA_COLOR;201012;SECTION_SOLID;.537254929542542;.486274510622025;.266666680574
$417;1.;
$ANSA_COLOR;201021;SECTION_SHELL;.768627464771271;0.34901961684227;.196078434586
$525;1.;
$ANSA_COLOR;201022;SECTION_SOLID;.545098066329956;.352941185235977;.184313729405
$403;1.;
$ANSA_COLOR;201025;SECTION_SHELL;.854901969432831;.019607843831182;.388235300779
$343;1.;
$ANSA_COLOR;201026;SECTION_SHELL;.549019634723663;.321568638086319;.878431379795
$074;1.;
$ANSA_COLOR;201031;SECTION_SHELL;.776470601558685;.215686276555061;.117647059261
$799;1.;
$ANSA_COLOR;201032;SECTION_SOLID;.552941203117371;.219607844948769;0.10196078568
$697;1.;
$ANSA_COLOR;201033;SECTION_SHELL;.952941179275513;.556862771511078;.498039215803
$146;1.;
$ANSA_COLOR;201034;SECTION_SHELL;.647058844566345;.858823537826538;.988235294818
$878;1.;
$ANSA_COLOR;201035;SECTION_SHELL;.866666674613953;.886274516582489;0.30588236451
$149;1.;
$ANSA_COLOR;201036;SECTION_SHELL;.556862771511078;0.18823529779911;.796078443527
$222;1.;
$ANSA_COLOR;201041;SECTION_SHELL;.788235306739807;.082352943718433;.035294119268
$656;1.;
$ANSA_COLOR;201042;SECTION_SOLID;.560784339904785;.090196080505848;.023529412224
$889;1.;
$ANSA_COLOR;201043;SECTION_SHELL;.960784316062927;.423529416322708;.415686279535
$294;1.;
$ANSA_COLOR;201044;SECTION_SHELL;0.65490198135376;.725490212440491;.905882358551
$025;1.;
$ANSA_COLOR;201045;SECTION_SHELL;.874509811401367;.752941191196442;.223529413342
$476;1.;
$ANSA_COLOR;201046;SECTION_SHELL;0.5686274766922;.058823529630899;.7176470756530
$76;1.;
$ANSA_COLOR;201051;SECTION_SHELL;.796078443527222;.952941179275513;.952941179275
$513;1.;
$ANSA_COLOR;201052;SECTION_SOLID;.572549045085907;0.95686274766922;.941176474094
$391;1.;
$ANSA_COLOR;201053;SECTION_SHELL;.968627452850342;.290196090936661;.333333343267
$441;1.;
$ANSA_COLOR;201054;SECTION_SHELL;.662745118141174;.592156887054443;0.82745099067
$688;1.;
$ANSA_COLOR;201055;SECTION_SHELL;.882352948188782;.619607865810394;0.14509804546
$833;1.;
$ANSA_COLOR;201056;SECTION_SHELL;.576470613479614;.925490200519562;.635294139385
$223;1.;
$ANSA_COLOR;201061;SECTION_SHELL;.803921580314636;.819607853889465;.874509811401
$367;1.;
$ANSA_COLOR;201062;SECTION_SOLID;.580392181873322;.823529422283173;.862745106220
$245;1.;
$ANSA_COLOR;201063;SECTION_SHELL;.980392158031464;.156862750649452;.254901975393
$295;1.;
$ANSA_COLOR;201064;SECTION_SHELL;.670588254928589;.462745100259781;.745098054409
$027;1.;
$ANSA_COLOR;201065;SECTION_SHELL;.890196084976196;.490196079015732;.062745101749
$897;1.;
$ANSA_COLOR;201066;SECTION_SHELL;.584313750267029;.792156875133514;.552941203117
$371;1.;
$ANSA_COLOR;201071;SECTION_SHELL;.811764717102051;.686274528503418;.792156875133
$514;1.;
$ANSA_COLOR;201072;SECTION_SOLID;.588235318660736;.690196096897125;.780392169952
$393;1.;
$ANSA_COLOR;201073;SECTION_SHELL;.988235294818878;.023529412224889;.172549024224
$281;1.;
$ANSA_COLOR;201074;SECTION_SHELL;.678431391716003;.329411774873734;.662745118141
$174;1.;
$ANSA_COLOR;201075;SECTION_SHELL;.901960790157318;.356862753629684;.984313726425
$171;1.;
$ANSA_COLOR;201076;SECTION_SHELL;.592156887054443;.658823549747467;.474509805440
$903;1.;
$ANSA_COLOR;201104;SECTION_SHELL;.858823537826538;.250980406999588;.658823549747
$467;1.;
$ANSA_COLOR;201111;SECTION_SOLID;.650980412960052;.952941179275513;.752941191196
$442;1.;
$ANSA_COLOR;201112;SECTION_SHELL;.945098042488098;.917647063732147;.850980401039
$124;1.;
$ANSA_COLOR;201113;SECTION_SOLID;.572549045085907;.149019613862038;.482352942228
$317;1.;
$ANSA_COLOR;201114;SECTION_SHELL;.866666674613953;.117647059261799;.580392181873
$322;1.;
$ANSA_COLOR;201121;SECTION_SOLID;.658823549747467;.819607853889465;.670588254928
$589;1.;
$ANSA_COLOR;201122;SECTION_SHELL;.952941179275513;0.7843137383461;.7686274647712
$71;1.;
$ANSA_COLOR;201123;SECTION_SOLID;.580392181873322;.015686275437474;.400000005960
$464;1.;
$ANSA_COLOR;201124;SECTION_SHELL;.874509811401367;.984313726425171;.498039215803
$146;1.;
$ANSA_COLOR;201131;SECTION_SOLID;.666666686534882;.686274528503418;.588235318660
$736;1.;
$ANSA_COLOR;201132;SECTION_SHELL;.960784316062927;0.65490198135376;.690196096897
$125;1.;
$ANSA_COLOR;201133;SECTION_SOLID;.588235318660736;.882352948188782;.317647069692
$612;1.;
$ANSA_COLOR;201134;SECTION_SHELL;.882352948188782;.850980401039124;.415686279535
$294;1.;
$ANSA_COLOR;201141;SECTION_SOLID;.678431391716003;.552941203117371;.509803950786
$591;1.;
$ANSA_COLOR;201142;SECTION_SHELL;.972549021244049;.521568655967712;.607843160629
$272;1.;
$ANSA_COLOR;201143;SECTION_SOLID;.600000023841858;.749019622802734;.239215686917
$305;1.;
$ANSA_COLOR;201144;SECTION_SHELL;.894117653369904;.717647075653076;.337254911661
$148;1.;
$ANSA_COLOR;201151;SECTION_SOLID;.686274528503418;.419607847929001;.427450984716
$415;1.;
$ANSA_COLOR;201152;SECTION_SHELL;.980392158031464;.388235300779343;0.52549022436
$142;1.;
$ANSA_COLOR;201153;SECTION_SOLID;.607843160629272;.615686297416687;.156862750649
$452;1.;
$ANSA_COLOR;201154;SECTION_SHELL;.901960790157318;.584313750267029;.254901975393
$295;1.;
$ANSA_COLOR;201161;SECTION_SOLID;.694117665290833;.286274522542953;.345098048448
$563;1.;
$ANSA_COLOR;201162;SECTION_SHELL;.988235294818878;.254901975393295;.447058826684
$952;1.;
$ANSA_COLOR;201163;SECTION_SOLID;.615686297416687;.482352942228317;.074509806931
$019;1.;
$ANSA_COLOR;201164;SECTION_SHELL;.909803926944733;.450980395078659;.172549024224
$281;1.;
$ANSA_COLOR;201171;SECTION_SOLID;.701960802078247;.152941182255745;.266666680574
$417;1.;
$ANSA_COLOR;201172;SECTION_SHELL;.996078431606293;.121568627655506;.364705890417
$099;1.;
$ANSA_COLOR;201173;SECTION_SOLID;.623529434204102;.352941185235977;.996078431606
$293;1.;
$ANSA_COLOR;201174;SECTION_SHELL;.917647063732147;.317647069692612;.094117648899
$555;1.;
$ANSA_COLOR;201521;SECTION_SHELL;0.82745099067688;.031372550874949;.552941203117
$371;1.;
$ANSA_COLOR;201522;SECTION_SHELL;.917647063732147;.701960802078247;0.74117648601
$532;1.;
$ANSA_COLOR;201523;SECTION_SHELL;.678431391716003;.709803938865662;.313725501298
$904;1.;
$ANSA_COLOR;201524;SECTION_SHELL;.501960813999176;.372549027204514;.933333337306
$976;1.;
$ANSA_COLOR;201525;SECTION_SHELL;.592156887054443;0.04313725605607;.121568627655
$506;1.;
$ANSA_COLOR;201531;SECTION_SHELL;.835294127464294;.898039221763611;.470588237047
$195;1.;
$ANSA_COLOR;201532;SECTION_SHELL;.925490200519562;0.5686274766922;.6627451181411
$74;1.;
$ANSA_COLOR;201533;SECTION_SHELL;.686274528503418;.580392181873322;0.23137255012
$989;1.;
$ANSA_COLOR;201534;SECTION_SHELL;.509803950786591;.239215686917305;.850980401039
$124;1.;
$ANSA_COLOR;201535;SECTION_SHELL;.600000023841858;.909803926944733;0.04313725605
$607;1.;
$ANSA_COLOR;201541;SECTION_SHELL;.847058832645416;.764705896377563;0.39215686917
$305;1.;
$ANSA_COLOR;201542;SECTION_SHELL;.933333337306976;0.43529412150383;.580392181873
$322;1.;
$ANSA_COLOR;201543;SECTION_SHELL;.694117665290833;.447058826684952;.152941182255
$745;1.;
$ANSA_COLOR;201544;SECTION_SHELL;.521568655967712;.105882354080677;.772549033164
$978;1.;
$ANSA_COLOR;201545;SECTION_SHELL;.607843160629272;.776470601558685;.960784316062
$927;1.;
$ANSA_COLOR;201551;SECTION_SHELL;.854901969432831;.631372570991516;.309803932905
$197;1.;
$ANSA_COLOR;201552;SECTION_SHELL;.941176474094391;.301960796117783;.498039215803
$146;1.;
$ANSA_COLOR;201553;SECTION_SHELL;.701960802078247;.313725501298904;.070588238537
$312;1.;
$ANSA_COLOR;201554;SECTION_SHELL;.529411792755127;.972549021244049;.690196096897
$125;1.;
$ANSA_COLOR;201555;SECTION_SHELL;.615686297416687;.643137276172638;.878431379795
$074;1.;
$ANSA_COLOR;201561;SECTION_SHELL;.862745106220245;.498039215803146;.227450981736
$183;1.;
$ANSA_COLOR;201562;SECTION_SHELL;.949019610881805;.168627455830574;.419607847929
$001;1.;
$ANSA_COLOR;201563;SECTION_SHELL;.713725507259369;.180392161011696;.988235294818
$878;1.;
$ANSA_COLOR;201564;SECTION_SHELL;.537254929542542;.839215695858002;.607843160629
$272;1.;
$ANSA_COLOR;201565;SECTION_SHELL;.623529434204102;.509803950786591;.800000011920
$929;1.;
$ANSA_COLOR;201571;SECTION_SHELL;0.87058824300766;.368627458810806;.149019613862
$038;1.;
$ANSA_COLOR;201572;SECTION_SHELL;.960784316062927;.035294119268656;.337254911661
$148;1.;
$ANSA_COLOR;201573;SECTION_SHELL;.721568644046783;.047058824449778;.909803926944
$733;1.;
$ANSA_COLOR;201574;SECTION_SHELL;.545098066329956;.705882370471954;.529411792755
$127;1.;
$ANSA_COLOR;201575;SECTION_SHELL;.635294139385223;.376470595598221;.717647075653
$076;1.;
$ANSA_COLOR;202021;SECTION_SOLID;.992156863212585;.345098048448563;.207843139767
$647;1.;
$ANSA_COLOR;202022;SECTION_SOLID;.564705908298492;.317647069692612;.294117659330
$368;1.;
$ANSA_COLOR;202031;SECTION_SOLID;.501960813999176;.211764708161354;.129411771893
$501;1.;
$ANSA_COLOR;202032;SECTION_SOLID;.572549045085907;.184313729405403;.215686276555
$061;1.;
$ANSA_COLOR;202041;SECTION_SOLID;.509803950786591;.078431375324726;.047058824449
$778;1.;
$ANSA_COLOR;202042;SECTION_SOLID;.580392181873322;.050980392843485;.133333340287
$209;1.;
$ANSA_COLOR;202051;SECTION_SOLID;.521568655967712;.949019610881805;.964705884456
$635;1.;
$ANSA_COLOR;202052;SECTION_SOLID;.588235318660736;.917647063732147;.054901961237
$192;1.;
$ANSA_COLOR;202061;SECTION_SOLID;.529411792755127;.815686285495758;.886274516582
$489;1.;
$ANSA_COLOR;202062;SECTION_SOLID;.600000023841858;0.7843137383461;.9725490212440
$49;1.;
$ANSA_COLOR;202071;SECTION_SOLID;.537254929542542;.682352960109711;.803921580314
$636;1.;
$ANSA_COLOR;202072;SECTION_SOLID;.607843160629272;.650980412960052;.890196084976
$196;1.;
$ANSA_COLOR;202121;SECTION_SHELL;.803921580314636;.011764706112444;.411764711141
$586;1.;
$ANSA_COLOR;202122;SECTION_SHELL;.894117653369904;.682352960109711;.603921592235
$565;1.;
$ANSA_COLOR;202123;SECTION_SHELL;.980392158031464;.352941185235977;.792156875133
$514;1.;
$ANSA_COLOR;202124;SECTION_SHELL;0.5686274766922;.023529412224889;.9843137264251
$71;1.;
$ANSA_COLOR;202125;SECTION_SHELL;0.65490198135376;.690196096897125;.172549024224
$281;1.;
$ANSA_COLOR;202126;SECTION_SHELL;0.74117648601532;.360784322023392;.360784322023
$392;1.;
$ANSA_COLOR;202131;SECTION_SHELL;.815686285495758;.878431379795074;.329411774873
$734;1.;
$ANSA_COLOR;202132;SECTION_SHELL;.901960790157318;.549019634723663;.521568655967
$712;1.;
$ANSA_COLOR;202133;SECTION_SHELL;.988235294818878;.219607844948769;.709803938865
$662;1.;
$ANSA_COLOR;202134;SECTION_SHELL;.576470613479614;.890196084976196;.901960790157
$318;1.;
$ANSA_COLOR;202135;SECTION_SHELL;.662745118141174;.560784339904785;.090196080505
$848;1.;
$ANSA_COLOR;202136;SECTION_SHELL;.749019622802734;.227450981736183;.282352954149
$246;1.;
$ANSA_COLOR;202141;SECTION_SHELL;.823529422283173;.745098054409027;.250980406999
$588;1.;
$ANSA_COLOR;202142;SECTION_SHELL;.909803926944733;.415686279535294;.439215689897
$537;1.;
$ANSA_COLOR;202143;SECTION_SHELL;.996078431606293;.086274512112141;.631372570991
$516;1.;
$ANSA_COLOR;202144;SECTION_SHELL;.584313750267029;.756862759590149;.819607853889
$465;1.;
$ANSA_COLOR;202145;SECTION_SHELL;.670588254928589;.427450984716415;.011764706112
$444;1.;
$ANSA_COLOR;202146;SECTION_SHELL;.756862759590149;.094117648899555;.200000002980
$232;1.;
$ANSA_COLOR;202151;SECTION_SHELL;.831372559070587;0.61176472902298;.168627455830
$574;1.;
$ANSA_COLOR;202152;SECTION_SHELL;.917647063732147;.282352954149246;.360784322023
$392;1.;
$ANSA_COLOR;202153;SECTION_SHELL;.505882382392883;.952941179275513;.549019634723
$663;1.;
$ANSA_COLOR;202154;SECTION_SHELL;.592156887054443;.623529434204102;0.74117648601
$532;1.;
$ANSA_COLOR;202155;SECTION_SHELL;.678431391716003;.294117659330368;.929411768913
$269;1.;
$ANSA_COLOR;202156;SECTION_SHELL;.768627464771271;.964705884456635;.121568627655
$506;1.;
$ANSA_COLOR;202161;SECTION_SHELL;.839215695858002;0.47843137383461;.086274512112
$141;1.;
$ANSA_COLOR;202162;SECTION_SHELL;.925490200519562;.149019613862038;.278431385755
$539;1.;
$ANSA_COLOR;202163;SECTION_SHELL;.513725519180298;.819607853889465;.466666668653
$488;1.;
$ANSA_COLOR;202164;SECTION_SHELL;.600000023841858;.490196079015732;.658823549747
$467;1.;
$ANSA_COLOR;202165;SECTION_SHELL;.690196096897125;.160784319043159;.847058832645
$416;1.;
$ANSA_COLOR;202166;SECTION_SHELL;.776470601558685;.831372559070587;.039215687662
$363;1.;
$ANSA_COLOR;202171;SECTION_SHELL;.847058832645416;.345098048448563;.007843137718
$737;1.;
$ANSA_COLOR;202172;SECTION_SHELL;.937254905700684;.015686275437474;.196078434586
$525;1.;
$ANSA_COLOR;202173;SECTION_SHELL;.521568655967712;.686274528503418;.388235300779
$343;1.;
$ANSA_COLOR;202174;SECTION_SHELL;0.61176472902298;.356862753629684;.576470613479
$614;1.;
$ANSA_COLOR;202175;SECTION_SHELL;0.69803923368454;.027450980618596;.768627464771
$271;1.;
$ANSA_COLOR;202176;SECTION_SHELL;0.7843137383461;0.69803923368454;0.956862747669
$22;1.;
$ANSA_COLOR;203001;SECTION_SOLID;.933333337306976;.470588237047195;.313725501298
$904;1.;
$ANSA_COLOR;203002;SECTION_SHELL;1.;.894117653369904;.768627464771271;0.5;
$ANSA_COLOR;203003;SECTION_SHELL;.780392169952393;.447058826684952;.388235300779
$343;1.;
$ANSA_COLOR;203004;SECTION_SHELL;.788235306739807;.313725501298904;.309803932905
$197;1.;
$ANSA_COLOR;203005;SECTION_SHELL;.745098054409027;.490196079015732;.862745106220
$245;1.;
$ANSA_COLOR;214002;SECTION_BEAM_ELFORM_1;.756862759590149;.356862753629684;.7803
$92169952393;1.;
$ANSA_COLOR;250560;SECTION_SHELL;.858823537826538;.984313726425171;.603921592235
$565;1.;
$ANSA_COLOR;250730;SECTION_SHELL;.717647075653076;.780392169952393;.039215687662
$363;1.;
$ANSA_COLOR;251111;SECTION_SOLID;.898039221763611;.972549021244049;0.69803923368
$454;1.;
$ANSA_COLOR;251112;SECTION_SHELL;.588235318660736;.490196079015732;.345098048448
$563;1.;
$ANSA_COLOR;251113;SECTION_SOLID;0.61176472902298;0.5686274766922;.5647059082984
$92;1.;
$ANSA_COLOR;251114;SECTION_SHELL;.709803938865662;.035294119268656;.082352943718
$433;1.;
$ANSA_COLOR;251121;SECTION_SOLID;0.7843137383461;.156862750649452;.0627451017498
$97;1.;
$ANSA_COLOR;251122;SECTION_SHELL;.627451002597809;.811764717102051;.580392181873
$322;1.;
$ANSA_COLOR;251123;SECTION_SOLID;.615686297416687;.090196080505848;.050980392843
$485;1.;
$ANSA_COLOR;251124;SECTION_SHELL;0.87058824300766;.901960790157318;.054901961237
$192;1.;
$ANSA_COLOR;251131;SECTION_SOLID;.650980412960052;.996078431606293;.894117653369
$904;1.;
$ANSA_COLOR;251132;SECTION_SHELL;.650980412960052;.627451002597809;.054901961237
$192;1.;
$ANSA_COLOR;251133;SECTION_SOLID;.792156875133514;.886274516582489;.168627455830
$574;1.;
$ANSA_COLOR;251134;SECTION_SHELL;.701960802078247;.674509823322296;.819607853889
$465;1.;
$ANSA_COLOR;251141;SECTION_SOLID;.862745106220245;.854901969432831;.082352943718
$433;1.;
$ANSA_COLOR;251142;SECTION_SHELL;.517647087574005;.466666668653488;.886274516582
$489;1.;
$ANSA_COLOR;251143;SECTION_SOLID;.815686285495758;.701960802078247;.643137276172
$638;1.;
$ANSA_COLOR;251144;SECTION_SHELL;.882352948188782;.466666668653488;.937254905700
$684;1.;
$ANSA_COLOR;251151;SECTION_SOLID;.580392181873322;.501960813999176;.498039215803
$146;1.;
$ANSA_COLOR;251152;SECTION_SHELL;.556862771511078;.423529416322708;.278431385755
$539;1.;
$ANSA_COLOR;251153;SECTION_SOLID;.674509823322296;.968627452850342;.015686275437
$474;1.;
$ANSA_COLOR;251154;SECTION_SHELL;.564705908298492;.047058824449778;.286274522542
$953;1.;
$ANSA_COLOR;251161;SECTION_SOLID;0.5686274766922;.250980406999588;.9058823585510
$25;1.;
$ANSA_COLOR;251162;SECTION_SHELL;.701960802078247;.149019613862038;.333333343267
$441;1.;
$ANSA_COLOR;251163;SECTION_SOLID;.976470589637756;.674509823322296;.713725507259
$369;1.;
$ANSA_COLOR;251164;SECTION_SHELL;.517647087574005;.729411780834198;.627451002597
$809;1.;
$ANSA_COLOR;251171;SECTION_SOLID;.898039221763611;.235294118523598;.439215689897
$537;1.;
$ANSA_COLOR;251172;SECTION_SHELL;.517647087574005;.780392169952393;.176470592617
$989;1.;
$ANSA_COLOR;251173;SECTION_SOLID;0.7843137383461;.949019610881805;0.870588243007
$66;1.;
$ANSA_COLOR;251174;SECTION_SHELL;.815686285495758;.647058844566345;.098039217293
$262;1.;
$ANSA_COLOR;401014;SECTION_SHELL;.905882358551025;.011764706112444;.494117647409
$439;1.;
$ANSA_COLOR;401211;SECTION_SOLID;.937254905700684;.701960802078247;.015686275437
$474;1.;
$ANSA_COLOR;401212;SECTION_SHELL;.733333349227905;.670588254928589;.113725490868
$092;1.;
$ANSA_USER_ATTRIBUTES;SECTION_SHELL;User/cad_material;TEXT;RW;YES;;;
$ANSA_USER_ATTRIBUTES;SECTION_SHELL;User/cad_thickness;TEXT;RW;YES;;;
$ANSA_USER_ATTRIBUTES;SECTION_SOLID;User/cad_material;TEXT;RW;YES;;;
*END
