$
$ANSA_VERSION;22.0.0;
$
$
$ file created by  A N S A  Mon Feb  7 12:25:43 2022
$
$ output from :
$
$ C:/Users/jobinj/Box/vivaplus-share/VIVA-Plus-Meshing-Shared-Folder/v0_3/vivapl
$ us-50F_v030_211214.ansa
$
$ Settings :
$
$ Output format : 971R9
$
$ Output : All
$
$ANSA_USER_ATTRIBUTES;vivaplus-controls.k;INCLUDE;DM/Status;TEXT;WIP;DM/IO Index
$;TEXT;;
$
$
$
$
$
$
$ANSA_COLOR;vivaplus-controls.k;INCLUDE;.733333349227905;.200000002980232;.54901
$9634723663;1.;
*KEYWORD
*END
