$
$ANSA_VERSION;21.1.0;
$
$
$ file created by  A N S A  Tue Apr 13 12:03:47 2021
$
$ output from :
$
$ C:/Users/iraeus/Documents/Projects/VIRTUAL/ViVA+/Final_assembly/vivaplus-50F_v
$ 0-2-2d.ansa
$
$ Settings :
$
$ Output format : R12
$
$ Output : All
$
$ANSA_USER_ATTRIBUTES;vivaplus-20-Neck.k;INCLUDE;DM/Status;TEXT;WIP;
$
$
$
$
$
$
$ANSA_COLOR;vivaplus-20-Neck.k;INCLUDE;.603921592235565;0.52549022436142;.168627
$455830574;1.;
*KEYWORD
*PART
NE_Hyoid
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200101    200101    200101                             0         0          
*SECTION_SHELL_TITLE
NE_Hyoid
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200101         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
NE-ligament-OC-C1-AAOM-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200510    200510    203009                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-AAOM-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200510         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.9       0.9       0.9       0.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Apical-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200520    200520    203014                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Apical-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200520         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Cruciform-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200530    200530    203013                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Cruciform-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200530         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Tectoria-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200540    200540    203015                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Tectoria-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200540         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       2.5       2.5       2.5       2.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Alar-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200550    200550    213019                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Alar-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200550         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       2.9       2.9       2.9       2.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-ligament-OC-C1-AOCJ-CL-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200560    200560    213014                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-AOCJ-CL-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200560         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-PAOM-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200570    200570    203008                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-PAOM-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200570         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.9       0.9       0.9       0.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-OC-C1-Transverse-C
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200580    200580    203016                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-Transverse-C
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200580         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE_L_Stylohyoid_Ligament
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    200610    200610    200610                             0                    
*SECTION_BEAM_TITLE
NE_L_Stylohyoid_Ligament
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    200610         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
    317.16        0.                  4.        0.        0.        0.        0.
*PART
NE-ligament-C1-C2-ALL-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200710    200710    203011                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-ALL-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200710         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-AAAM-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200720    200720    203012                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-AAAM-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200720         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.9       0.9       0.9       0.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-ligament-C1-C2-CL-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200730    200730    213015                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-CL-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200730         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-IL-Cruciform-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200740    200740    203018                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-IL-Cruciform-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200740         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-Transverse-Center-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200750    200750    203019                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-Transverse-Center-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200750         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligament-C1-C2-PAAM-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    200760    200760    203017                             0         0          
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-PAAM-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    200760         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.9       0.9       0.9       0.9        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-Vertebra-C1-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201011    201011    200011                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.5        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C1-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201011         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.46      0.46      0.46      0.46        0.                  0.          
*PART
NE-Vertebra-C1-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201012    201012    200012                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C1-Trabecular-M
$    SECID|   ELFORM|
    201012        13
*PART_CONTACT
NE-Vertebra-C2-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201021    201021    200021                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.5        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C2-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201021         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.46      0.46      0.46      0.46        0.                  0.          
*PART
NE-Vertebra-C2-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201022    201022    200022                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C2-Trabecular-M
$    SECID|   ELFORM|
    201022        13
*PART
NE-Vertebra-C2-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201025    201025    200024                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C2-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201025         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.58      0.58      0.58      0.58        0.                  0.          
*PART
NE-Vertebra-C2-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201026    201026    203020                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C2-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201026         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C3-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201031    201031    200031                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.5        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201031         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.46      0.46      0.46      0.46        0.                  0.          
*PART
NE-Vertebra-C3-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201032    201032    200032                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C3-Trabecular-M
$    SECID|   ELFORM|
    201032        13
*PART
NE-Vertebra-C3-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201033    201033    200023                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201033         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.63      0.63      0.63      0.63        0.                  0.          
*PART
NE-Vertebra-C3-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201034    201034    203029                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201034         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C3-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201035    201035    200034                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201035         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.58      0.58      0.58      0.58        0.                  0.          
*PART
NE-Vertebra-C3-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201036    201036    203030                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C3-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201036         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C4-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201041    201041    200041                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.5        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201041         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.48      0.48      0.48      0.48        0.                  0.          
*PART
NE-Vertebra-C4-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201042    201042    200042                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C4-Trabecular-M
$    SECID|   ELFORM|
    201042        13
*PART
NE-Vertebra-C4-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201043    201043    200033                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201043         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.62      0.62      0.62      0.62        0.                  0.          
*PART
NE-Vertebra-C4-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201044    201044    203039                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201044         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C4-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201045    201045    200044                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201045         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.56      0.56      0.56      0.56        0.                  0.          
*PART
NE-Vertebra-C4-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201046    201046    203040                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C4-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201046         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C5-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201051    201051    200051                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.3        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201051         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
NE-Vertebra-C5-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201052    201052    200052                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C5-Trabecular-M
$    SECID|   ELFORM|
    201052        13
*PART
NE-Vertebra-C5-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201053    201053    200043                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201053         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.55      0.55      0.55      0.55        0.                  0.          
*PART
NE-Vertebra-C5-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201054    201054    203049                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201054         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C5-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201055    201055    200054                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201055         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.62      0.62      0.62      0.62        0.                  0.          
*PART
NE-Vertebra-C5-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201056    201056    203050                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C5-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201056         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C6-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201061    201061    200061                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.4        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201061         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.58      0.58      0.58      0.58        0.                  0.          
*PART
NE-Vertebra-C6-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201062    201062    200062                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C6-Trabecular-M
$    SECID|   ELFORM|
    201062        13
*PART
NE-Vertebra-C6-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201063    201063    200053                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201063         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.63      0.63      0.63      0.63        0.                  0.          
*PART
NE-Vertebra-C6-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201064    201064    203059                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201064         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C6-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201065    201065    200064                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201065         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.65      0.65      0.65      0.65        0.                  0.          
*PART
NE-Vertebra-C6-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201066    201066    203060                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C6-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201066         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART_CONTACT
NE-Vertebra-C7-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201071    201071    200071                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.4        0.
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201071         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.59      0.59      0.59      0.59        0.                  0.          
*PART
NE-Vertebra-C7-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201072    201072    200072                             0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-C7-Trabecular-M
$    SECID|   ELFORM|
    201072        13
*PART
NE-Vertebra-C7-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201073    201073    200063                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201073         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.6       0.6       0.6       0.6        0.                  0.          
*PART
NE-Vertebra-C7-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201074    201074    203069                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201074         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-C7-Endplate-inferior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201075    201075    200074                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Endplate-inferior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201075         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.67      0.67      0.67      0.67        0.                  0.          
*PART
NE-Vertebra-C7-Endplate-inferior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201076    201076    203070                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-C7-Endplate-inferior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201076         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
NE-Vertebra-Articular-Process-OC-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201104    201104    213011                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-OC-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201104         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C1-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201111    201111    213013             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C1-Superior-Cartilage-L
$    SECID|   ELFORM|
    201111         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C1-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201112    201112    213012                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C1-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201112         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C1-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201113    201113    213016             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C1-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201113         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C1-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201114    201114    213017                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C1-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201114         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C2-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201121    201121    213010             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C2-Superior-Cartilage-L
$    SECID|   ELFORM|
    201121         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C2-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201122    201122    213018                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C2-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201122         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C2-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201123    201123    213022             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C2-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201123         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C2-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201124    201124    213024                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C2-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201124         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C3-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201131    201131    213023             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C3-Superior-Cartilage-L
$    SECID|   ELFORM|
    201131         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C3-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201132    201132    213025                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C3-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201132         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C3-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201133    201133    213032             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C3-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201133         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C3-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201134    201134    213034                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C3-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201134         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C4-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201141    201141    213033             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C4-Superior-Cartilage-L
$    SECID|   ELFORM|
    201141         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C4-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201142    201142    213035                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C4-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201142         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C4-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201143    201143    213042             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C4-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201143         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C4-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201144    201144    213044                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C4-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201144         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C5-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201151    201151    213043             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C5-Superior-Cartilage-L
$    SECID|   ELFORM|
    201151         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C5-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201152    201152    213045                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C5-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201152         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C5-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201153    201153    213052             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C5-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201153         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C5-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201154    201154    213054                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C5-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201154         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C6-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201161    201161    213053             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C6-Superior-Cartilage-L
$    SECID|   ELFORM|
    201161         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C6-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201162    201162    213055                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C6-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201162         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C6-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201163    201163    213062             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C6-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201163         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C6-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201164    201164    213064                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C6-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201164         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C7-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201171    201171    213063             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C7-Superior-Cartilage-L
$    SECID|   ELFORM|
    201171         1
*PART_CONTACT
NE-Vertebra-Articular-Process-C7-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201172    201172    213065                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C7-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201172         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C7-Inferior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    201173    201173    213072             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C7-Inferior-Cartilage-L
$    SECID|   ELFORM|
    201173         1
*PART
NE-Vertebra-Articular-Process-C7-Inferior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201174    201174    213074                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C7-Inferior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201174         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-ligaments-C2-C3-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201521    201521    213028                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201521         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C2-C3-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201522    201522    213027                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201522         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-ligaments-C2-C3-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201523    201523    213021                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201523         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C2-C3-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201524    201524    213026                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201524         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C2-C3-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201525    201525    213029                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C2-C3-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201525         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.4       1.4       1.4       1.4        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C3-C4-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201531    201531    213038                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201531         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C3-C4-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201532    201532    213037                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201532         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-ligaments-C3-C4-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201533    201533    213031                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201533         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C3-C4-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201534    201534    213036                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201534         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C3-C4-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201535    201535    213039                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C3-C4-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201535         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.4       1.4       1.4       1.4        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C4-C5-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201541    201541    213048                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201541         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C4-C5-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201542    201542    213047                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201542         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-ligaments-C4-C5-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201543    201543    213041                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201543         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C4-C5-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201544    201544    213046                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201544         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C4-C5-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201545    201545    213049                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C4-C5-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201545         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.4       1.4       1.4       1.4        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C5-C6-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201551    201551    213058                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201551         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C5-C6-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201552    201552    213057                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201552         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-ligaments-C5-C6-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201553    201553    213051                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201553         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C5-C6-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201554    201554    213056                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201554         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C5-C6-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201555    201555    213059                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C5-C6-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201555         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.4       1.4       1.4       1.4        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C6-C7-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201561    201561    213068                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201561         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C6-C7-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201562    201562    213067                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201562         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-ligaments-C6-C7-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201563    201563    213061                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201563         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C6-C7-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201564    201564    213066                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201564         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C6-C7-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201565    201565    213069                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C6-C7-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201565         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C7-T1-ALL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201571    201571    213078                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-ALL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201571         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.5       1.5       1.5       1.5        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C7-T1-PLL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201572    201572    213077                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-PLL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201572         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.7       1.7       1.7       1.7        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-ligaments-C7-T1-CL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201573    201573    213071                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.5        0.        0.
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-CL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201573         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C7-T1-LF-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201574    201574    213076                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-LF-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201574         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.3       1.3       1.3       1.3        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-ligaments-C7-T1-ISL-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    201575    201575    213079                             0         0          
*SECTION_SHELL_TITLE
NE-ligaments-C7-T1-ISL-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    201575         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-C2-C3-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202021    202021    203022            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C2-C3-Annulus-ground-M
$    SECID|   ELFORM|
    202021         1
*PART
NE-IVD-C2-C3-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202022    202022    203021            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C2-C3-Nucleus-M
$    SECID|   ELFORM|
    202022         1
*PART
NE-IVD-C3-C4-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202031    202031    203032            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C3-C4-Annulus-ground-M
$    SECID|   ELFORM|
    202031         1
*PART
NE-IVD-C3-C4-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202032    202032    203031            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C3-C4-Nucleus-M
$    SECID|   ELFORM|
    202032         1
*PART
NE-IVD-C4-C5-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202041    202041    203042            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C4-C5-Annulus-ground-M
$    SECID|   ELFORM|
    202041         1
*PART
NE-IVD-C4-C5-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202042    202042    203041            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C4-C5-Nucleus-M
$    SECID|   ELFORM|
    202042         1
*PART
NE-IVD-C5-C6-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202051    202051    203052            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C5-C6-Annulus-ground-M
$    SECID|   ELFORM|
    202051         1
*PART
NE-IVD-C5-C6-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202052    202052    203051            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C5-C6-Nucleus-M
$    SECID|   ELFORM|
    202052         1
*PART
NE-IVD-C6-C7-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202061    202061    203062            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C6-C7-Annulus-ground-M
$    SECID|   ELFORM|
    202061         1
*PART
NE-IVD-C6-C7-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202062    202062    203061            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C6-C7-Nucleus-M
$    SECID|   ELFORM|
    202062         1
*PART
NE-IVD-C7-T1-Annulus-ground-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202071    202071    203072            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C7-T1-Annulus-ground-M
$    SECID|   ELFORM|
    202071         1
*PART
NE-IVD-C7-T1-Nucleus-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    202072    202072    203071            41110000         0         0          
*SECTION_SOLID_TITLE
NE-IVD-C7-T1-Nucleus-M
$    SECID|   ELFORM|
    202072         1
*PART
NE-IVD-Annulus-fiber-C2-C3-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202121    202121    203023                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202121         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202122    202122    203024                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202122         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202123    202123    203025                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202123         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202124    202124    203026                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202124         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202125    202125    203027                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202125         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C2-C3-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202126    202126    203028                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C2-C3-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202126         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202131    202131    203033                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202131         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202132    202132    203034                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202132         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202133    202133    203035                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202133         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202134    202134    203036                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202134         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202135    202135    203037                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202135         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C3-C4-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202136    202136    203038                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C3-C4-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202136         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202141    202141    203043                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202141         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202142    202142    203044                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202142         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202143    202143    203045                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202143         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202144    202144    203046                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202144         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202145    202145    203047                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202145         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C4-C5-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202146    202146    203048                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C4-C5-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202146         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202151    202151    203053                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202151         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202152    202152    203054                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202152         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202153    202153    203055                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202153         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202154    202154    203056                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202154         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202155    202155    203057                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202155         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C5-C6-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202156    202156    203058                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C5-C6-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202156         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202161    202161    203063                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202161         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202162    202162    203064                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202162         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202163    202163    203065                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202163         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202164    202164    203066                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202164         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202165    202165    203067                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202165         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C6-C7-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202166    202166    203068                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C6-C7-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202166         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-1a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202171    202171    203073                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-1a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202171         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-1b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202172    202172    203074                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-1b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202172         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-2a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202173    202173    203075                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-2a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202173         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-2b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202174    202174    203076                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-2b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202174         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-3a-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202175    202175    203077                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-3a-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202175         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-IVD-Annulus-fiber-C7-T1-3b-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    202176    202176    203078                             0         0          
*SECTION_SHELL_TITLE
NE-IVD-Annulus-fiber-C7-T1-3b-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    202176         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE_Neck_Soft_Tissues
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    203001    203001    405100             2000000         0         0          
*SECTION_SOLID_TITLE
NE_Neck_Soft_Tissues
$    SECID|   ELFORM|
    203001         1
*PART
NE_Skin
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    203002    203002    906001                             0         0          
*SECTION_SHELL_TITLE
NE_Skin
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    203002         9   0.83333        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE_Soft_Tissue_Interior
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    203003    203003    203003                             0         0          
*SECTION_SHELL_TITLE
NE_Soft_Tissue_Interior
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    203003         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
NE_Trachea
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    203004    203004    203004                             0         0          
*SECTION_SHELL_TITLE
NE_Trachea
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    203004         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
NE_Larynx
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    203005    203005    203005                             0         0          
*SECTION_SHELL_TITLE
NE_Larynx
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    203005         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
NE_C_Tracheal_Cartilage
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    214002    214002    214002                             0                    
*SECTION_BEAM_TITLE
NE_C_Tracheal_Cartilage
$    SECID|   ELFORM|     SHRF|  QT/IRID|      CST|         |      NSM|
    214002         1   0.83333         2        0.                  0.
$      TS1|      TS2|      TT1|      TT2|    NSLOC|    NTLOC|
        1.        1.        1.        1.        0.        0.
*PART_CONTACT
NE-ligament-OC-C1-AOCJ-CL-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    250560    250560    213014                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-ligament-OC-C1-AOCJ-CL-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    250560         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART_CONTACT
NE-ligament-C1-C2-CL-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    250730    250730    213015                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.1        0.        0.
*SECTION_SHELL_TITLE
NE-ligament-C1-C2-CL-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    250730         9     0.833        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       1.1       1.1       1.1       1.1        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
NE-Vertebra-Articular-Process-C1-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251111    251111    213013             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C1-Superior-Cartilage-R
$    SECID|   ELFORM|
    251111         1
*PART
NE-Vertebra-Articular-Process-C1-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251112    251112    213012                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C1-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251112         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C1-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251113    251113    213016             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C1-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251113         1
*PART
NE-Vertebra-Articular-Process-C1-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251114    251114    213017                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C1-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251114         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C2-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251121    251121    213010             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C2-Superior-Cartilage-R
$    SECID|   ELFORM|
    251121         1
*PART
NE-Vertebra-Articular-Process-C2-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251122    251122    213018                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C2-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251122         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C2-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251123    251123    213022             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C2-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251123         1
*PART
NE-Vertebra-Articular-Process-C2-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251124    251124    213024                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C2-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251124         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C3-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251131    251131    213023             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C3-Superior-Cartilage-R
$    SECID|   ELFORM|
    251131         1
*PART
NE-Vertebra-Articular-Process-C3-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251132    251132    213025                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C3-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251132         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C3-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251133    251133    213032             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C3-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251133         1
*PART
NE-Vertebra-Articular-Process-C3-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251134    251134    213034                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C3-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251134         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C4-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251141    251141    213033             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C4-Superior-Cartilage-R
$    SECID|   ELFORM|
    251141         1
*PART
NE-Vertebra-Articular-Process-C4-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251142    251142    213035                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C4-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251142         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C4-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251143    251143    213042             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C4-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251143         1
*PART
NE-Vertebra-Articular-Process-C4-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251144    251144    213044                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C4-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251144         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C5-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251151    251151    213043             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C5-Superior-Cartilage-R
$    SECID|   ELFORM|
    251151         1
*PART
NE-Vertebra-Articular-Process-C5-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251152    251152    213045                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C5-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251152         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C5-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251153    251153    213052             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C5-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251153         1
*PART
NE-Vertebra-Articular-Process-C5-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251154    251154    213054                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C5-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251154         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C6-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251161    251161    213053             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C6-Superior-Cartilage-R
$    SECID|   ELFORM|
    251161         1
*PART
NE-Vertebra-Articular-Process-C6-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251162    251162    213055                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C6-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251162         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C6-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251163    251163    213062             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C6-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251163         1
*PART
NE-Vertebra-Articular-Process-C6-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251164    251164    213064                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C6-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251164         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C7-Superior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251171    251171    213063             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C7-Superior-Cartilage-R
$    SECID|   ELFORM|
    251171         1
*PART
NE-Vertebra-Articular-Process-C7-Superior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251172    251172    213065                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C7-Superior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251172         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
*PART
NE-Vertebra-Articular-Process-C7-Inferior-Cartilage-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    251173    251173    213072             2000000         0         0          
*SECTION_SOLID_TITLE
NE-Vertebra-Articular-Process-C7-Inferior-Cartilage-R
$    SECID|   ELFORM|
    251173         1
*PART
NE-Vertebra-Articular-Process-C7-Inferior-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    251174    251174    213074                             0         0          
*SECTION_SHELL_TITLE
NE-Vertebra-Articular-Process-C7-Inferior-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    251174         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.06      0.06      0.06      0.06        0.                  0.          
*PART
TX-Spine-T1-Endplate-superior-null-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401014    401014    203079                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T1-Endplate-superior-null-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401014         2   0.83333        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.1       0.1       0.1       0.1        0.                  0.          
*PART
TX-Vertebra-Articular-Process-T1-Superior-Cartilage-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401211    401211    213073             2000000         0         0          
*SECTION_SOLID_TITLE
TX-Vertebra-Articular-Process-T1-Superior-Cartilage-L
$    SECID|   ELFORM|
    401211         1
*PART
TX-Vertebra-Articular-Process-T1-Superior-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401212    401212    213075                             0         0          
*SECTION_SHELL_TITLE
TX-Vertebra-Articular-Process-T1-Superior-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401212         5     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.25      0.25      0.25      0.25        0.                  0.          
$ANSA_COLOR;200101;SECTION_SHELL;.682352960109711;.749019622802734;.474509805440
$903;1.;
$ANSA_COLOR;200510;SECTION_SHELL;.749019622802734;.352941185235977;.352941185235
$977;1.;
$ANSA_COLOR;200520;SECTION_SHELL;.839215695858002;.023529412224889;.541176497936
$249;1.;
$ANSA_COLOR;200530;SECTION_SHELL;.925490200519562;.690196096897125;.733333349227
$905;1.;
$ANSA_COLOR;200540;SECTION_SHELL;.513725519180298;.360784322023392;.921568632125
$854;1.;
$ANSA_COLOR;200550;SECTION_SHELL;.600000023841858;.031372550874949;.113725490868
$092;1.;
$ANSA_COLOR;200560;SECTION_SHELL;.686274528503418;.701960802078247;.301960796117
$783;1.;
$ANSA_COLOR;200570;SECTION_SHELL;.772549033164978;.372549027204514;.494117647409
$439;1.;
$ANSA_COLOR;200580;SECTION_SHELL;.862745106220245;0.04313725605607;.682352960109
$711;1.;
$ANSA_COLOR;200610;SECTION_BEAM_ELFORM_6;.623529434204102;.050980392843485;.2549
$01975393295;1.;
$ANSA_COLOR;200710;SECTION_SHELL;.996078431606293;.752941191196442;.152941182255
$745;1.;
$ANSA_COLOR;200720;SECTION_SHELL;.584313750267029;.419607847929001;.345098048448
$563;1.;
$ANSA_COLOR;200730;SECTION_SHELL;.670588254928589;.090196080505848;.533333361148
$834;1.;
$ANSA_COLOR;200740;SECTION_SHELL;.756862759590149;.760784327983856;.725490212440
$491;1.;
$ANSA_COLOR;200750;SECTION_SHELL;.843137264251709;.431372553110123;0.91372549533
$844;1.;
$ANSA_COLOR;200760;SECTION_SHELL;.933333337306976;0.10196078568697;.105882354080
$677;1.;
$ANSA_COLOR;201011;SECTION_SHELL;.619607865810394;.717647075653076;.776470601558
$685;1.;
$ANSA_COLOR;201012;SECTION_SOLID;.631372570991516;.584313750267029;.694117665290
$833;1.;
$ANSA_COLOR;201021;SECTION_SHELL;.709803938865662;.388235300779343;.968627452850
$342;1.;
$ANSA_COLOR;201022;SECTION_SOLID;.717647075653076;.254901975393295;.886274516582
$489;1.;
$ANSA_COLOR;201025;SECTION_SHELL;.745098054409027;.854901969432831;.643137276172
$638;1.;
$ANSA_COLOR;201026;SECTION_SHELL;.752941191196442;.721568644046783;.560784339904
$785;1.;
$ANSA_COLOR;201031;SECTION_SHELL;.796078443527222;.058823529630899;.156862750649
$452;1.;
$ANSA_COLOR;201032;SECTION_SOLID;.803921580314636;.925490200519562;.074509806931
$019;1.;
$ANSA_COLOR;201033;SECTION_SHELL;.811764717102051;.792156875133514;.996078431606
$293;1.;
$ANSA_COLOR;201034;SECTION_SHELL;.823529422283173;.658823549747467;0.91372549533
$844;1.;
$ANSA_COLOR;201035;SECTION_SHELL;.831372559070587;0.52549022436142;.831372559070
$587;1.;
$ANSA_COLOR;201036;SECTION_SHELL;.839215695858002;0.39215686917305;.752941191196
$442;1.;
$ANSA_COLOR;201041;SECTION_SHELL;.882352948188782;.725490212440491;0.34901961684
$227;1.;
$ANSA_COLOR;201042;SECTION_SOLID;.890196084976196;.592156887054443;.266666680574
$417;1.;
$ANSA_COLOR;201043;SECTION_SHELL;.901960790157318;.462745100259781;.184313729405
$403;1.;
$ANSA_COLOR;201044;SECTION_SHELL;.909803926944733;.329411774873734;.105882354080
$677;1.;
$ANSA_COLOR;201045;SECTION_SHELL;.917647063732147;.196078434586525;.023529412224
$889;1.;
$ANSA_COLOR;201046;SECTION_SHELL;.925490200519562;.062745101749897;.941176474094
$391;1.;
$ANSA_COLOR;201051;SECTION_SHELL;.968627452850342;.396078437566757;.537254929542
$542;1.;
$ANSA_COLOR;201052;SECTION_SOLID;.980392158031464;0.26274511218071;.454901963472
$366;1.;
$ANSA_COLOR;201053;SECTION_SHELL;.988235294818878;.129411771893501;.376470595598
$221;1.;
$ANSA_COLOR;201054;SECTION_SHELL;.996078431606293;.996078431606293;.294117659330
$368;1.;
$ANSA_COLOR;201055;SECTION_SHELL;.505882382392883;.866666674613953;.211764708161
$354;1.;
$ANSA_COLOR;201056;SECTION_SHELL;.513725519180298;.733333349227905;.133333340287
$209;1.;
$ANSA_COLOR;201061;SECTION_SHELL;.556862771511078;.066666670143604;.729411780834
$198;1.;
$ANSA_COLOR;201062;SECTION_SOLID;.564705908298492;.933333337306976;.647058844566
$345;1.;
$ANSA_COLOR;201063;SECTION_SHELL;.576470613479614;.800000011920929;.564705908298
$492;1.;
$ANSA_COLOR;201064;SECTION_SHELL;.584313750267029;.666666686534882;.486274510622
$025;1.;
$ANSA_COLOR;201065;SECTION_SHELL;.592156887054443;.533333361148834;.403921574354
$172;1.;
$ANSA_COLOR;201066;SECTION_SHELL;.600000023841858;.400000005960464;.321568638086
$319;1.;
$ANSA_COLOR;201071;SECTION_SHELL;.643137276172638;.737254917621613;.917647063732
$147;1.;
$ANSA_COLOR;201072;SECTION_SOLID;0.65490198135376;.603921592235565;.835294127464
$294;1.;
$ANSA_COLOR;201073;SECTION_SHELL;.662745118141174;.470588237047195;.756862759590
$149;1.;
$ANSA_COLOR;201074;SECTION_SHELL;.670588254928589;.337254911661148;.674509823322
$296;1.;
$ANSA_COLOR;201075;SECTION_SHELL;.678431391716003;0.20392157137394;.592156887054
$443;1.;
$ANSA_COLOR;201076;SECTION_SHELL;.690196096897125;.070588238537312;.513725519180
$298;1.;
$ANSA_COLOR;201104;SECTION_SHELL;.933333337306976;0.34901961684227;0.24705882370
$472;1.;
$ANSA_COLOR;201111;SECTION_SOLID;.992156863212585;.415686279535294;.678431391716
$003;1.;
$ANSA_COLOR;201112;SECTION_SHELL;.501960813999176;.282352954149246;.596078455448
$151;1.;
$ANSA_COLOR;201113;SECTION_SOLID;.509803950786591;.149019613862038;.517647087574
$005;1.;
$ANSA_COLOR;201114;SECTION_SHELL;.521568655967712;.015686275437474;0.43529412150
$383;1.;
$ANSA_COLOR;201121;SECTION_SOLID;.580392181873322;.086274512112141;.866666674613
$953;1.;
$ANSA_COLOR;201122;SECTION_SHELL;.588235318660736;.952941179275513;.788235306739
$807;1.;
$ANSA_COLOR;201123;SECTION_SOLID;.600000023841858;.819607853889465;.705882370471
$954;1.;
$ANSA_COLOR;201124;SECTION_SHELL;.607843160629272;.686274528503418;.623529434204
$102;1.;
$ANSA_COLOR;201131;SECTION_SOLID;.666666686534882;.756862759590149;.058823529630
$899;1.;
$ANSA_COLOR;201132;SECTION_SHELL;.678431391716003;.623529434204102;.976470589637
$756;1.;
$ANSA_COLOR;201133;SECTION_SOLID;.686274528503418;.490196079015732;.898039221763
$611;1.;
$ANSA_COLOR;201134;SECTION_SHELL;.694117665290833;.356862753629684;.815686285495
$758;1.;
$ANSA_COLOR;201141;SECTION_SOLID;.756862759590149;.427450984716415;0.24705882370
$472;1.;
$ANSA_COLOR;201142;SECTION_SHELL;.764705896377563;.294117659330368;.168627455830
$574;1.;
$ANSA_COLOR;201143;SECTION_SOLID;.772549033164978;.160784319043159;.086274512112
$141;1.;
$ANSA_COLOR;201144;SECTION_SHELL;.780392169952393;.027450980618596;.003921568859
$369;1.;
$ANSA_COLOR;201151;SECTION_SOLID;.843137264251709;.098039217293262;.439215689897
$537;1.;
$ANSA_COLOR;201152;SECTION_SHELL;.850980401039124;.964705884456635;.356862753629
$684;1.;
$ANSA_COLOR;201153;SECTION_SOLID;.858823537826538;.831372559070587;.278431385755
$539;1.;
$ANSA_COLOR;201154;SECTION_SHELL;0.87058824300766;0.69803923368454;.196078434586
$525;1.;
$ANSA_COLOR;201161;SECTION_SOLID;.929411768913269;.764705896377563;.627451002597
$809;1.;
$ANSA_COLOR;201162;SECTION_SHELL;.937254905700684;.635294139385223;.549019634723
$663;1.;
$ANSA_COLOR;201163;SECTION_SOLID;.949019610881805;.501960813999176;.466666668653
$488;1.;
$ANSA_COLOR;201164;SECTION_SHELL;0.95686274766922;.368627458810806;.384313732385
$635;1.;
$ANSA_COLOR;201171;SECTION_SOLID;.517647087574005;0.43529412150383;.819607853889
$465;1.;
$ANSA_COLOR;201172;SECTION_SHELL;0.52549022436142;.301960796117783;.737254917621
$613;1.;
$ANSA_COLOR;201173;SECTION_SOLID;.533333361148834;.168627455830574;.658823549747
$467;1.;
$ANSA_COLOR;201174;SECTION_SHELL;.545098066329956;.039215687662363;.576470613479
$614;1.;
$ANSA_COLOR;201521;SECTION_SHELL;.572549045085907;.886274516582489;.474509805440
$903;1.;
$ANSA_COLOR;201522;SECTION_SHELL;.580392181873322;.752941191196442;0.39215686917
$305;1.;
$ANSA_COLOR;201523;SECTION_SHELL;.588235318660736;.619607865810394;.309803932905
$197;1.;
$ANSA_COLOR;201524;SECTION_SHELL;.596078455448151;.486274510622025;0.23137255012
$989;1.;
$ANSA_COLOR;201525;SECTION_SHELL;.603921592235565;.352941185235977;.149019613862
$038;1.;
$ANSA_COLOR;201531;SECTION_SHELL;.658823549747467;.556862771511078;.662745118141
$174;1.;
$ANSA_COLOR;201532;SECTION_SHELL;.666666686534882;.423529416322708;.584313750267
$029;1.;
$ANSA_COLOR;201533;SECTION_SHELL;.674509823322296;.290196090936661;.501960813999
$176;1.;
$ANSA_COLOR;201534;SECTION_SHELL;.682352960109711;.156862750649452;.419607847929
$001;1.;
$ANSA_COLOR;201535;SECTION_SHELL;.694117665290833;.023529412224889;.341176480054
$855;1.;
$ANSA_COLOR;201541;SECTION_SHELL;.745098054409027;.223529413342476;.854901969432
$831;1.;
$ANSA_COLOR;201542;SECTION_SHELL;.752941191196442;.090196080505848;.772549033164
$978;1.;
$ANSA_COLOR;201543;SECTION_SHELL;.760784327983856;.960784316062927;.690196096897
$125;1.;
$ANSA_COLOR;201544;SECTION_SHELL;.772549033164978;0.82745099067688;0.61176472902
$298;1.;
$ANSA_COLOR;201545;SECTION_SHELL;.780392169952393;.694117665290833;.529411792755
$127;1.;
$ANSA_COLOR;201551;SECTION_SHELL;.831372559070587;.894117653369904;0.04313725605
$607;1.;
$ANSA_COLOR;201552;SECTION_SHELL;.843137264251709;.760784327983856;.960784316062
$927;1.;
$ANSA_COLOR;201553;SECTION_SHELL;.850980401039124;.627451002597809;.882352948188
$782;1.;
$ANSA_COLOR;201554;SECTION_SHELL;.858823537826538;.494117647409439;.800000011920
$929;1.;
$ANSA_COLOR;201555;SECTION_SHELL;.866666674613953;.364705890417099;.721568644046
$783;1.;
$ANSA_COLOR;201561;SECTION_SHELL;.921568632125854;.564705908298492;.235294118523
$598;1.;
$ANSA_COLOR;201562;SECTION_SHELL;.929411768913269;.431372553110123;.152941182255
$745;1.;
$ANSA_COLOR;201563;SECTION_SHELL;.937254905700684;.298039227724075;.070588238537
$312;1.;
$ANSA_COLOR;201564;SECTION_SHELL;.945098042488098;.164705887436867;.992156863212
$585;1.;
$ANSA_COLOR;201565;SECTION_SHELL;.952941179275513;.031372550874949;.909803926944
$733;1.;
$ANSA_COLOR;201571;SECTION_SHELL;.505882382392883;.235294118523598;.423529416322
$708;1.;
$ANSA_COLOR;201572;SECTION_SHELL;.517647087574005;0.10196078568697;.341176480054
$855;1.;
$ANSA_COLOR;201573;SECTION_SHELL;0.52549022436142;.968627452850342;0.26274511218
$071;1.;
$ANSA_COLOR;201574;SECTION_SHELL;.533333361148834;.835294127464294;.180392161011
$696;1.;
$ANSA_COLOR;201575;SECTION_SHELL;.541176497936249;.701960802078247;.098039217293
$262;1.;
$ANSA_COLOR;202021;SECTION_SOLID;.933333337306976;.384313732385635;.980392158031
$464;1.;
$ANSA_COLOR;202022;SECTION_SOLID;.941176474094391;.250980406999588;.898039221763
$611;1.;
$ANSA_COLOR;202031;SECTION_SOLID;.521568655967712;.050980392843485;.168627455830
$574;1.;
$ANSA_COLOR;202032;SECTION_SOLID;.529411792755127;.921568632125854;.090196080505
$848;1.;
$ANSA_COLOR;202041;SECTION_SOLID;.607843160629272;.721568644046783;.360784322023
$392;1.;
$ANSA_COLOR;202042;SECTION_SOLID;.615686297416687;.588235318660736;.278431385755
$539;1.;
$ANSA_COLOR;202051;SECTION_SOLID;.694117665290833;0.39215686917305;.549019634723
$663;1.;
$ANSA_COLOR;202052;SECTION_SOLID;.701960802078247;.258823543787003;.470588237047
$195;1.;
$ANSA_COLOR;202061;SECTION_SOLID;.780392169952393;.062745101749897;0.74117648601
$532;1.;
$ANSA_COLOR;202062;SECTION_SOLID;.792156875133514;.929411768913269;.658823549747
$467;1.;
$ANSA_COLOR;202071;SECTION_SOLID;0.87058824300766;.733333349227905;.929411768913
$269;1.;
$ANSA_COLOR;202072;SECTION_SOLID;.878431379795074;.600000023841858;.850980401039
$124;1.;
$ANSA_COLOR;202121;SECTION_SHELL;.803921580314636;.082352943718433;.882352948188
$782;1.;
$ANSA_COLOR;202122;SECTION_SHELL;.815686285495758;.949019610881805;.800000011920
$929;1.;
$ANSA_COLOR;202123;SECTION_SHELL;.823529422283173;.815686285495758;.717647075653
$076;1.;
$ANSA_COLOR;202124;SECTION_SHELL;.831372559070587;.682352960109711;.639215707778
$931;1.;
$ANSA_COLOR;202125;SECTION_SHELL;.839215695858002;.549019634723663;.556862771511
$078;1.;
$ANSA_COLOR;202126;SECTION_SHELL;.847058832645416;.415686279535294;.474509805440
$903;1.;
$ANSA_COLOR;202131;SECTION_SHELL;.894117653369904;.752941191196442;.070588238537
$312;1.;
$ANSA_COLOR;202132;SECTION_SHELL;.901960790157318;.619607865810394;.988235294818
$878;1.;
$ANSA_COLOR;202133;SECTION_SHELL;.909803926944733;.486274510622025;.909803926944
$733;1.;
$ANSA_COLOR;202134;SECTION_SHELL;.917647063732147;.352941185235977;0.82745099067
$688;1.;
$ANSA_COLOR;202135;SECTION_SHELL;.929411768913269;.219607844948769;.745098054409
$027;1.;
$ANSA_COLOR;202136;SECTION_SHELL;.937254905700684;.086274512112141;.666666686534
$882;1.;
$ANSA_COLOR;202141;SECTION_SHELL;.980392158031464;.423529416322708;0.26274511218
$071;1.;
$ANSA_COLOR;202142;SECTION_SHELL;.988235294818878;.290196090936661;.180392161011
$696;1.;
$ANSA_COLOR;202143;SECTION_SHELL;.996078431606293;.156862750649452;.098039217293
$262;1.;
$ANSA_COLOR;202144;SECTION_SHELL;.505882382392883;.023529412224889;.019607843831
$182;1.;
$ANSA_COLOR;202145;SECTION_SHELL;.513725519180298;.890196084976196;.937254905700
$684;1.;
$ANSA_COLOR;202146;SECTION_SHELL;.521568655967712;.756862759590149;.854901969432
$831;1.;
$ANSA_COLOR;202151;SECTION_SHELL;0.5686274766922;.094117648899555;.4509803950786
$59;1.;
$ANSA_COLOR;202152;SECTION_SHELL;.576470613479614;.960784316062927;.368627458810
$806;1.;
$ANSA_COLOR;202153;SECTION_SHELL;.584313750267029;0.82745099067688;.290196090936
$661;1.;
$ANSA_COLOR;202154;SECTION_SHELL;.592156887054443;.694117665290833;.207843139767
$647;1.;
$ANSA_COLOR;202155;SECTION_SHELL;.603921592235565;.560784339904785;.125490203499
$794;1.;
$ANSA_COLOR;202156;SECTION_SHELL;0.61176472902298;.427450984716415;.047058824449
$778;1.;
$ANSA_COLOR;202161;SECTION_SHELL;0.65490198135376;.760784327983856;.639215707778
$931;1.;
$ANSA_COLOR;202162;SECTION_SHELL;.662745118141174;.627451002597809;.560784339904
$785;1.;
$ANSA_COLOR;202163;SECTION_SHELL;.670588254928589;.498039215803146;0.47843137383
$461;1.;
$ANSA_COLOR;202164;SECTION_SHELL;.682352960109711;.364705890417099;.400000005960
$464;1.;
$ANSA_COLOR;202165;SECTION_SHELL;.690196096897125;0.23137255012989;.317647069692
$612;1.;
$ANSA_COLOR;202166;SECTION_SHELL;0.69803923368454;.098039217293262;.235294118523
$598;1.;
$ANSA_COLOR;202171;SECTION_SHELL;0.74117648601532;.431372553110123;.831372559070
$587;1.;
$ANSA_COLOR;202172;SECTION_SHELL;.749019622802734;.298039227724075;.749019622802
$734;1.;
$ANSA_COLOR;202173;SECTION_SHELL;.760784327983856;.164705887436867;.670588254928
$589;1.;
$ANSA_COLOR;202174;SECTION_SHELL;.768627464771271;.031372550874949;.588235318660
$736;1.;
$ANSA_COLOR;202175;SECTION_SHELL;.776470601558685;.901960790157318;.505882382392
$883;1.;
$ANSA_COLOR;202176;SECTION_SHELL;0.7843137383461;.768627464771271;.4274509847164
$15;1.;
$ANSA_COLOR;203001;SECTION_SOLID;.984313726425171;.039215687662363;0.61176472902
$298;1.;
$ANSA_COLOR;203002;SECTION_SHELL;.992156863212585;.905882358551025;.529411792755
$127;1.;
$ANSA_COLOR;203003;SECTION_SHELL;.501960813999176;.772549033164978;.450980395078
$659;1.;
$ANSA_COLOR;203004;SECTION_SHELL;.509803950786591;.639215707778931;.368627458810
$806;1.;
$ANSA_COLOR;203005;SECTION_SHELL;.517647087574005;.505882382392883;.286274522542
$953;1.;
$ANSA_COLOR;214002;SECTION_BEAM_ELFORM_1;0.95686274766922;.858823537826538;.6666
$66686534882;1.;
$ANSA_COLOR;250560;SECTION_SHELL;.901960790157318;.498039215803146;.921568632125
$854;1.;
$ANSA_COLOR;250730;SECTION_SHELL;.882352948188782;.886274516582489;.152941182255
$745;1.;
$ANSA_COLOR;251111;SECTION_SOLID;.705882370471954;.211764708161354;.294117659330
$368;1.;
$ANSA_COLOR;251112;SECTION_SHELL;.717647075653076;.078431375324726;.215686276555
$061;1.;
$ANSA_COLOR;251113;SECTION_SOLID;.725490212440491;.945098042488098;.133333340287
$209;1.;
$ANSA_COLOR;251114;SECTION_SHELL;.733333349227905;.811764717102051;.050980392843
$485;1.;
$ANSA_COLOR;251121;SECTION_SOLID;.796078443527222;.882352948188782;.486274510622
$025;1.;
$ANSA_COLOR;251122;SECTION_SHELL;.803921580314636;.749019622802734;.403921574354
$172;1.;
$ANSA_COLOR;251123;SECTION_SOLID;.811764717102051;.615686297416687;.325490206480
$026;1.;
$ANSA_COLOR;251124;SECTION_SHELL;.819607853889465;.482352942228317;.243137255311
$012;1.;
$ANSA_COLOR;251131;SECTION_SOLID;.882352948188782;.549019634723663;.674509823322
$296;1.;
$ANSA_COLOR;251132;SECTION_SHELL;.890196084976196;.419607847929001;.596078455448
$151;1.;
$ANSA_COLOR;251133;SECTION_SOLID;.898039221763611;.286274522542953;.513725519180
$298;1.;
$ANSA_COLOR;251134;SECTION_SHELL;.909803926944733;.152941182255745;.431372553110
$123;1.;
$ANSA_COLOR;251141;SECTION_SOLID;.968627452850342;.219607844948769;.866666674613
$953;1.;
$ANSA_COLOR;251142;SECTION_SHELL;.976470589637756;.086274512112141;0.78431373834
$61;1.;
$ANSA_COLOR;251143;SECTION_SOLID;.988235294818878;.952941179275513;.701960802078
$247;1.;
$ANSA_COLOR;251144;SECTION_SHELL;.996078431606293;.823529422283173;.623529434204
$102;1.;
$ANSA_COLOR;251151;SECTION_SOLID;.556862771511078;.890196084976196;.054901961237
$192;1.;
$ANSA_COLOR;251152;SECTION_SHELL;.564705908298492;.756862759590149;.976470589637
$756;1.;
$ANSA_COLOR;251153;SECTION_SOLID;.572549045085907;.623529434204102;.894117653369
$904;1.;
$ANSA_COLOR;251154;SECTION_SHELL;.584313750267029;.490196079015732;.811764717102
$051;1.;
$ANSA_COLOR;251161;SECTION_SOLID;.643137276172638;.560784339904785;0.24705882370
$472;1.;
$ANSA_COLOR;251162;SECTION_SHELL;.650980412960052;.427450984716415;.164705887436
$867;1.;
$ANSA_COLOR;251163;SECTION_SOLID;.662745118141174;.294117659330368;.082352943718
$433;1.;
$ANSA_COLOR;251164;SECTION_SHELL;.670588254928589;.160784319043159;.003921568859
$369;1.;
$ANSA_COLOR;251171;SECTION_SOLID;.729411780834198;0.23137255012989;0.43529412150
$383;1.;
$ANSA_COLOR;251172;SECTION_SHELL;0.74117648601532;.098039217293262;.356862753629
$684;1.;
$ANSA_COLOR;251173;SECTION_SOLID;.749019622802734;.964705884456635;.274509817361
$832;1.;
$ANSA_COLOR;251174;SECTION_SHELL;.756862759590149;.831372559070587;.192156866192
$818;1.;
$ANSA_COLOR;401014;SECTION_SHELL;.501960813999176;.494117647409439;.003921568859
$369;1.;
$ANSA_COLOR;401211;SECTION_SOLID;.721568644046783;.294117659330368;.047058824449
$778;1.;
$ANSA_COLOR;401212;SECTION_SHELL;.729411780834198;.160784319043159;.968627452850
$342;1.;
$ANSA_USER_ATTRIBUTES;SECTION_SHELL;User/cad_material;TEXT;RW;YES;;;
$ANSA_USER_ATTRIBUTES;SECTION_SHELL;User/cad_thickness;TEXT;RW;YES;;;
$ANSA_USER_ATTRIBUTES;SECTION_SOLID;User/cad_material;TEXT;RW;YES;;;
*END
