$
$ANSA_VERSION;22.0.1;
$
$
$ file created by  A N S A  Fri Apr 29 11:31:46 2022
$
$ output from :
$
$ C:/Users/iraeus/Documents/Projects/VIRTUAL/ViVA+/RELEASES/vivaplus-v0-3-0rc5/5
$ 0F-seated/vivaplus-50F.key
$
$ Settings :
$
$ Output format : 971R9
$
$ Output : All
$
$ANSA_USER_ATTRIBUTES;vivaplus-40-Thorax.k;INCLUDE;DM/Status;TEXT;WIP;DM/IO Inde
$x;TEXT;;
$
$
$
$
$
$
$ANSA_COLOR;vivaplus-40-Thorax.k;INCLUDE;.996078431606293;0.;.400000005960464;1.
$;
*KEYWORD
*PART_CONTACT
TX-Spine-T1-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401011    401011    400011                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.        0.       0.4        0.
*SECTION_SHELL_TITLE
TX-Spine-T1-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401011         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T1-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401012    401012    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T1-Trabecular-M
$    SECID|   ELFORM|
    401012        13
*PART
TX-Spine-T1-Endplate-superior-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401013    401013    200021                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T1-Endplate-superior-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401013         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.6       0.6       0.6       0.6        0.                  0.          
*PART
TX-Spine-T2-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401021    401021    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T2-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401021         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T2-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401022    401022    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T2-Trabecular-M
$    SECID|   ELFORM|
    401022        13
*PART
TX-Spine-T3-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401031    401031    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T3-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401031         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T3-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401032    401032    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T3-Trabecular-M
$    SECID|   ELFORM|
    401032        13
*PART
TX-Spine-T4-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401041    401041    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T4-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401041         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T4-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401042    401042    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T4-Trabecular-M
$    SECID|   ELFORM|
    401042        13
*PART
TX-Spine-T5-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401051    401051    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T5-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401051         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T5-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401052    401052    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T5-Trabecular-M
$    SECID|   ELFORM|
    401052        13
*PART
TX-Spine-T6-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401061    401061    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T6-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401061         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T6-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401062    401062    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T6-Trabecular-M
$    SECID|   ELFORM|
    401062        13
*PART
TX-Spine-T7-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401071    401071    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T7-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401071         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T7-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401072    401072    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T7-Trabecular-M
$    SECID|   ELFORM|
    401072        13
*PART
TX-Spine-T8-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401081    401081    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T8-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401081         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T8-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401082    401082    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T8-Trabecular-M
$    SECID|   ELFORM|
    401082        13
*PART
TX-Spine-T9-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401091    401091    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T9-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401091         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T9-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401092    401092    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T9-Trabecular-M
$    SECID|   ELFORM|
    401092        13
*PART
TX-Spine-T10-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401101    401101    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T10-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401101         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T10-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401102    401102    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T10-Trabecular-M
$    SECID|   ELFORM|
    401102        13
*PART
TX-Spine-T11-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401111    401111    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T11-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401111         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T11-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401112    401112    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T11-Trabecular-M
$    SECID|   ELFORM|
    401112        13
*PART
TX-Spine-T12-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    401121    401121    400011                             0         0          
*SECTION_SHELL_TITLE
TX-Spine-T12-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    401121         4   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
      0.53      0.53      0.53      0.53        0.                  0.          
*PART
TX-Spine-T12-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    401122    401122    400012                             0         0          
*SECTION_SOLID_TITLE
TX-Spine-T12-Trabecular-M
$    SECID|   ELFORM|
    401122        13
*PART
TX-IVD-T1-T2-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402010    402010    402010                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T1-T2-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402010         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400001        0.        0.        0.        0.        0.
*PART
TX-IVD-T2-T3-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402020    402020    402020                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T2-T3-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402020         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400002        0.        0.        0.        0.        0.
*PART
TX-IVD-T3-T4-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402030    402030    402030                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T3-T4-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402030         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400003        0.        0.        0.        0.        0.
*PART
TX-IVD-T4-T5-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402040    402040    402040                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T4-T5-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402040         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400004        0.        0.        0.        0.        0.
*PART
TX-IVD-T5-T6-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402050    402050    402050                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T5-T6-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402050         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400005        0.        0.        0.        0.        0.
*PART
TX-IVD-T6-T7-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402060    402060    402060                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T6-T7-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402060         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400006        0.        0.        0.        0.        0.
*PART
TX-IVD-T7-T8-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402070    402070    402070                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T7-T8-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402070         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400007        0.        0.        0.        0.        0.
*PART
TX-IVD-T8-T9-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402080    402080    402080                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T8-T9-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402080         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400008        0.        0.        0.        0.        0.
*PART
TX-IVD-T9-T10-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402090    402090    402090                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T9-T10-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402090         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400009        0.        0.        0.        0.        0.
*PART
TX-IVD-T10-T11-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402100    402100    402100                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T10-T11-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402100         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400010        0.        0.        0.        0.        0.
*PART
TX-IVD-T11-T12-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402110    402110    402110                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T11-T12-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402110         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400011        0.        0.        0.        0.        0.
*PART
TX-IVD-T12-L1-Joint-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    402120    402120    402120                             0                    
*SECTION_BEAM_TITLE
TX-IVD-T12-L1-Joint-M
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    402120         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
     8000.        1.    400012        0.        0.        0.        0.        0.
*PART
TX-Ribcage-R1-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403013    403013    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R1-Trabecular-L
$    SECID|   ELFORM|
    403013         1
*PART_CONTACT
TX-Ribcage-R1-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403014    403014    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R1-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403014        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R1-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403015    403015    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R1-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403015        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R2-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403023    403023    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R2-Trabecular-L
$    SECID|   ELFORM|
    403023         1
*PART_CONTACT
TX-Ribcage-R2-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403024    403024    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R2-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403024        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R2-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403025    403025    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R2-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403025        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R3-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403033    403033    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R3-Trabecular-L
$    SECID|   ELFORM|
    403033         1
*PART_CONTACT
TX-Ribcage-R3-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403034    403034    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R3-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403034        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R3-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403035    403035    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R3-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403035        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R4-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403043    403043    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R4-Trabecular-L
$    SECID|   ELFORM|
    403043         1
*PART_CONTACT
TX-Ribcage-R4-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403044    403044    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R4-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403044        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R4-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403045    403045    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R4-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403045        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R5-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403053    403053    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R5-Trabecular-L
$    SECID|   ELFORM|
    403053         1
*PART_CONTACT
TX-Ribcage-R5-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403054    403054    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R5-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403054        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R5-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403055    403055    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R5-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403055        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R6-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403063    403063    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R6-Trabecular-L
$    SECID|   ELFORM|
    403063         1
*PART_CONTACT
TX-Ribcage-R6-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403064    403064    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R6-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403064        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R6-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403065    403065    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R6-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403065        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R7-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403073    403073    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R7-Trabecular-L
$    SECID|   ELFORM|
    403073         1
*PART_CONTACT
TX-Ribcage-R7-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403074    403074    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R7-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403074        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R7-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403075    403075    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R7-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403075        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R8-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403083    403083    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R8-Trabecular-L
$    SECID|   ELFORM|
    403083         1
*PART_CONTACT
TX-Ribcage-R8-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403084    403084    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R8-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403084        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R8-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403085    403085    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R8-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403085        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R9-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403093    403093    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R9-Trabecular-L
$    SECID|   ELFORM|
    403093         1
*PART_CONTACT
TX-Ribcage-R9-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403094    403094    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R9-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403094        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R9-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403095    403095    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R9-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403095        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R10-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403103    403103    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R10-Trabecular-L
$    SECID|   ELFORM|
    403103         1
*PART_CONTACT
TX-Ribcage-R10-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403104    403104    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R10-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403104        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R10-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403105    403105    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R10-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403105        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R11-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403113    403113    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R11-Trabecular-L
$    SECID|   ELFORM|
    403113         1
*PART_CONTACT
TX-Ribcage-R11-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403114    403114    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R11-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403114        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R11-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403115    403115    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R11-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403115        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R12-Trabecular-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403123    403123    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R12-Trabecular-L
$    SECID|   ELFORM|
    403123         1
*PART_CONTACT
TX-Ribcage-R12-Cortical-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403124    403124    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R12-Cortical-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403124        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R12-Cortical-Posterior-End-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403125    403125    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R12-Cortical-Posterior-End-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403125        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-Sternum-Cortical-M
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403501    403501    401001              900003         0         0          
*SECTION_SHELL_TITLE
TX-Ribcage-Sternum-Cortical-M
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403501        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
TX-Ribcage-Sternum-Trabecular-M
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403502    403502    401002              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-Sternum-Trabecular-M
$    SECID|   ELFORM|
    403502         1
*PART
TX-Ribcage-Sternum-Rigid-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403503    403503    401003              900003         0         0          
*SECTION_SHELL_TITLE
TX-Ribcage-Sternum-Rigid-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403503        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
TX-Ribcage-Cartilage-Exterior-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403601    403601    403111              900002         0         0          
*SECTION_SHELL_TITLE
TX-Ribcage-Cartilage-Exterior-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403601         2      0.83        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
*PART
TX-Ribcage-Cartilage-Solid-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    403602    403602    403111              403602         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-Cartilage-Solid-L
$    SECID|   ELFORM|
    403602         1
*PART_CONTACT
TX-Ribcage-Costochondral_Junction-Exterior-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403603    403603    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-Costochondral_Junction-Exterior-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403603        16      0.83        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-Rigid_Deformable_Transition-Exterior-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    403604    403604    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-Rigid_Deformable_Transition-Exterior-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    403604        16      0.83        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Intercostal-External-T1-T12-Muscle-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    404001    404001    404111              900001         0         0          
*SECTION_SOLID_TITLE
TX-Intercostal-External-T1-T12-Muscle-L
$    SECID|   ELFORM|
    404001         1
*PART
TX-Intercostal-External-T1-T12-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    404009    404009    404119                             0         0          
*SECTION_SHELL_TITLE
TX-Intercostal-External-T1-T12-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    404009         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5                            0.          
*PART
TX-Intercostal-T1-T12-Null_edge-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    404010    404010    404119                             0         0          
*SECTION_SHELL_TITLE
TX-Intercostal-T1-T12-Null_edge-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    404010         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5                            0.          
*PART
TX-Intercostal-Internal-T1-T12-Muscle-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    404201    404201    404111              900001         0         0          
*SECTION_SOLID_TITLE
TX-Intercostal-Internal-T1-T12-Muscle-L
$    SECID|   ELFORM|
    404201         1
*PART
TX-Intercostal-Innermost-T1-T12-Muscle-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    404401    404401    404111              900001         0         0          
*SECTION_SOLID_TITLE
TX-Intercostal-Innermost-T1-T12-Muscle-L
$    SECID|   ELFORM|
    404401         1
*PART
TX-Intercostal-Innermost-T1-T12-Null-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    404409    404409    404119                             0         0          
*SECTION_SHELL_TITLE
TX-Intercostal-Innermost-T1-T12-Null-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    404409         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5                            0.          
*PART
TX-Muscle-Rhomboideus-Major-T1-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404501    404501    404501                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Rhomboideus-Major-T1-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404501         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      207.        0.        0.
*PART
TX-Muscle-Rhomboideus-Major-T2-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404502    404502    404501                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Rhomboideus-Major-T2-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404502         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      207.        0.        0.
*PART
TX-Muscle-Rhomboideus-Major-T3-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404503    404503    404501                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Rhomboideus-Major-T3-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404503         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      124.        0.        0.
*PART
TX-Muscle-Rhomboideus-Major-T4-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404504    404504    404501                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Rhomboideus-Major-T4-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404504         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      124.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T1-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404601    404601    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T1-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404601         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      345.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T2-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404602    404602    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T2-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404602         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T3-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404603    404603    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T3-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404603         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T4-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404604    404604    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T4-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404604         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T5-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404605    404605    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T5-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404605         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T6-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404606    404606    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T6-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404606         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T7-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404607    404607    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T7-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404607         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T8-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404608    404608    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T8-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404608         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T9-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404609    404609    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T9-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404609         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T10-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404610    404610    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T10-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404610         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T11-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404611    404611    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T11-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404611         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T12-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404612    404612    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T12-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404612         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib2-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404702    404702    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib2-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404702         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib3-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404703    404703    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib3-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404703         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib4-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404704    404704    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib4-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404704         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib5-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404705    404705    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib5-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404705         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib6-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404706    404706    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib6-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404706         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib7-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404707    404707    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib7-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404707         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib8-Scap-L-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    404708    404708    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib8-Scap-L-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    404708         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Thoracic_Cavity-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    405001    405001    405101              900001         0         0          
*SECTION_SOLID_TITLE
TX-Thoracic_Cavity-L
$    SECID|   ELFORM|
    405001         1
*PART
TX-Thoracic_Cavity-nulls-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    405003    405003    405009                             0         0          
*SECTION_SHELL_TITLE
TX-Thoracic_Cavity-nulls-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    405003         2     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
*PART
TX-Soft-Skin-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    406001    406001    100000                             0         0          
*SECTION_SHELL_TITLE
TX-Soft-Skin-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    406001         9   0.83333        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
TX-Soft_Tissues-L
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    406002    406002    405100              900001         0         0          
*SECTION_SOLID_TITLE
TX-Soft_Tissues-L
$    SECID|   ELFORM|
    406002         1
*PART
TX-Torso-Soft-Internal_nulls-L
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    406003    406003    406009                             0         0          
*SECTION_SHELL_TITLE
TX-Torso-Soft-Internal_nulls-L
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    406003         2   0.83333        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
TX-Torso-Soft-Internal_nulls-for-single-surface-contact
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    406013    406013    406009                             0         0          
*SECTION_SHELL_TITLE
TX-Torso-Soft-Internal_nulls-for-single-surface-contact
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    406013         2   0.83333        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
TX-Ribcage-R1-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453013    453013    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R1-Trabecular-R
$    SECID|   ELFORM|
    453013         1
*PART_CONTACT
TX-Ribcage-R1-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453014    453014    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R1-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453014        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R1-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453015    453015    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R1-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453015        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R2-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453023    453023    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R2-Trabecular-R
$    SECID|   ELFORM|
    453023         1
*PART_CONTACT
TX-Ribcage-R2-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453024    453024    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R2-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453024        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R2-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453025    453025    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R2-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453025        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R3-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453033    453033    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R3-Trabecular-R
$    SECID|   ELFORM|
    453033         1
*PART_CONTACT
TX-Ribcage-R3-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453034    453034    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R3-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453034        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R3-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453035    453035    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R3-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453035        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R4-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453043    453043    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R4-Trabecular-R
$    SECID|   ELFORM|
    453043         1
*PART_CONTACT
TX-Ribcage-R4-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453044    453044    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R4-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453044        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R4-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453045    453045    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R4-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453045        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R5-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453053    453053    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R5-Trabecular-R
$    SECID|   ELFORM|
    453053         1
*PART_CONTACT
TX-Ribcage-R5-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453054    453054    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R5-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453054        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R5-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453055    453055    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R5-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453055        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R6-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453063    453063    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R6-Trabecular-R
$    SECID|   ELFORM|
    453063         1
*PART_CONTACT
TX-Ribcage-R6-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453064    453064    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R6-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453064        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R6-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453065    453065    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R6-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453065        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R7-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453073    453073    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R7-Trabecular-R
$    SECID|   ELFORM|
    453073         1
*PART_CONTACT
TX-Ribcage-R7-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453074    453074    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R7-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453074        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R7-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453075    453075    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R7-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453075        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R8-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453083    453083    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R8-Trabecular-R
$    SECID|   ELFORM|
    453083         1
*PART_CONTACT
TX-Ribcage-R8-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453084    453084    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R8-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453084        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R8-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453085    453085    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R8-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453085        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R9-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453093    453093    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R9-Trabecular-R
$    SECID|   ELFORM|
    453093         1
*PART_CONTACT
TX-Ribcage-R9-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453094    453094    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R9-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453094        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R9-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453095    453095    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R9-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453095        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R10-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453103    453103    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R10-Trabecular-R
$    SECID|   ELFORM|
    453103         1
*PART_CONTACT
TX-Ribcage-R10-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453104    453104    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R10-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453104        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R10-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453105    453105    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R10-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453105        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R11-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453113    453113    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R11-Trabecular-R
$    SECID|   ELFORM|
    453113         1
*PART_CONTACT
TX-Ribcage-R11-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453114    453114    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R11-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453114        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R11-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453115    453115    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R11-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453115        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-R12-Trabecular-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453123    453123    403003              900001         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-R12-Trabecular-R
$    SECID|   ELFORM|
    453123         1
*PART_CONTACT
TX-Ribcage-R12-Cortical-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453124    453124    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R12-Cortical-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453124        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-R12-Cortical-Posterior-End-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453125    453125    403015              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-R12-Cortical-Posterior-End-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453125        16   0.83333        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Ribcage-Sternum--Rigid-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453503    453503    401003              900003         0         0          
*SECTION_SHELL_TITLE
TX-Ribcage-Sternum--Rigid-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453503        16        0.        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
TX-Ribcage-Cartilage-Exterior-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453601    453601    403111              900002         0         0          
*SECTION_SHELL_TITLE
TX-Ribcage-Cartilage-Exterior-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453601         2      0.83        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
*PART
TX-Ribcage-Cartilage-Solid-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    453602    453602    403111              403602         0         0          
*SECTION_SOLID_TITLE
TX-Ribcage-Cartilage-Solid-R
$    SECID|   ELFORM|
    453602         1
*PART_CONTACT
TX-Ribcage-Costochondral_Junction-Exterior-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453603    453603    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-Costochondral_Junction-Exterior-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453603        16      0.83        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART_CONTACT
TX-Ribcage-Rigid_Deformable_Transition-Exterior-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    453604    453604    403004              900003         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
                                               0.5                    
*SECTION_SHELL_TITLE
TX-Ribcage-Rigid_Deformable_Transition-Exterior-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    453604        16      0.83        5.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.7       0.7       0.7       0.7        0.                  0.          
*PART
TX-Intercostal-External-T1-T12-Muscle-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    454001    454001    404111              900001         0         0          
*SECTION_SOLID_TITLE
TX-Intercostal-External-T1-T12-Muscle-R
$    SECID|   ELFORM|
    454001         1
*PART
TX-Intercostal-External-T1-T12-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    454009    454009    404119                             0         0          
*SECTION_SHELL_TITLE
TX-Intercostal-External-T1-T12-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    454009         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5                            0.          
*PART
TX-Intercostal-T1-T12-Null_edge-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    454010    454010    404119                             0         0          
*SECTION_SHELL_TITLE
TX-Intercostal-T1-T12-Null_edge-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    454010         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5                            0.          
*PART
TX-Intercostal-Internal-T1-T12-Muscle-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    454201    454201    404111              900001         0         0          
*SECTION_SOLID_TITLE
TX-Intercostal-Internal-T1-T12-Muscle-R
$    SECID|   ELFORM|
    454201         1
*PART
TX-Intercostal-muscle-Intermost-T1-T12-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    454400    454400    404111              900001         0         0          
*SECTION_SOLID_TITLE
TX-Intercostal-muscle-Intermost-T1-T12-R
$    SECID|   ELFORM|
    454400         1
*PART
TX-Intercostal-Innermost-T1-T12-Null-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    454409    454409    404119                             0         0          
*SECTION_SHELL_TITLE
TX-Intercostal-Innermost-T1-T12-Null-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    454409         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5                            0.          
*PART
TX-Muscle-Rhomboideus-Major-T1-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454501    454501    404501                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Rhomboideus-Major-T1-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454501         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      207.        0.        0.
*PART
TX-Muscle-Rhomboideus-Major-T2-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454502    454502    404501                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Rhomboideus-Major-T2-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454502         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      207.        0.        0.
*PART
TX-Muscle-Rhomboideus-Major-T3-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454503    454503    404501                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Rhomboideus-Major-T3-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454503         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      124.        0.        0.
*PART
TX-Muscle-Rhomboideus-Major-T4-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454504    454504    404501                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Rhomboideus-Major-T4-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454504         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      124.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T1-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454601    454601    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T1-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454601         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      345.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T2-Scap-R-PCSA (Garner 2001)'
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454602    454602    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T2-Scap-R-PCSA (Garner 2001)'
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454602         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T3-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454603    454603    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T3-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454603         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T4-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454604    454604    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T4-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454604         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T5-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454605    454605    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T5-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454605         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T6-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454606    454606    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T6-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454606         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T7-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454607    454607    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T7-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454607         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T8-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454608    454608    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T8-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454608         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T9-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454609    454609    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T9-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454609         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T10-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454610    454610    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T10-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454610         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T11-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454611    454611    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T11-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454611         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Trapezius-Ascend-T12-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454612    454612    404601                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Trapezius-Ascend-T12-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454612         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      113.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib2-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454702    454702    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib2-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454702         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib3-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454703    454703    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib3-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454703         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib4-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454704    454704    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib4-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454704         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib5-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454705    454705    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib5-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454705         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib6-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454706    454706    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib6-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454706         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib7-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454707    454707    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib7-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454707         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Muscle-Serratus-Anterior-Rib8-Scap-R-PCSA (Garner 2001)
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    454708    454708    404701                             0                    
*SECTION_BEAM_TITLE
TX-Muscle-Serratus-Anterior-Rib8-Scap-R-PCSA (Garner 2001)
$    SECID|   ELFORM|         |  QR/IRID|      CST|         |      NSM|
    454708         3                  0.        0.                  0.
$        A|    RAMPT|   STRESS|
      293.        0.        0.
*PART
TX-Thoracic_Cavity-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    455001    455001    405101              900001         0         0          
*SECTION_SOLID_TITLE
TX-Thoracic_Cavity-R
$    SECID|   ELFORM|
    455001         1
*PART
TX-Thoracic_Cavity-nulls-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    455003    455003    405009                             0         0          
*SECTION_SHELL_TITLE
TX-Thoracic_Cavity-nulls-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    455003         2     0.833        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
       0.5       0.5       0.5       0.5        0.                  0.          
*PART
TX-Soft-Skin-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    456001    456001    100000                             0         0          
*SECTION_SHELL_TITLE
TX-Soft-Skin-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    456001         9   0.83333        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.      -90.
*PART
TX-Soft_Tissues-R
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    456002    456002    405100              900001         0         0          
*SECTION_SOLID_TITLE
TX-Soft_Tissues-R
$    SECID|   ELFORM|
    456002         1
*PART
TX-Torso-Soft-Internal_nulls-R
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    456003    456003    406009                             0         0          
*SECTION_SHELL_TITLE
TX-Torso-Soft-Internal_nulls-R
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    456003         2   0.83333        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
TX-Torso-Soft-Internal_nulls-for-single-surface-contact
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    456013    456013    406009                             0         0          
*SECTION_SHELL_TITLE
TX-Torso-Soft-Internal_nulls-for-single-surface-contact
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    456013         2   0.83333        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$ANSA_COLOR;401011;SECTION_SHELL;.541176497936249;.368627458810806;.623529434204
$102;1.;
$ANSA_COLOR;401012;SECTION_SOLID;.815686285495758;.372549027204514;0.61176472902
$298;1.;
$ANSA_COLOR;401013;SECTION_SHELL;.713725507259369;.709803938865662;.003921568859
$369;1.;
$ANSA_COLOR;401021;SECTION_SHELL;.549019634723663;.235294118523598;.541176497936
$249;1.;
$ANSA_COLOR;401022;SECTION_SOLID;.823529422283173;.239215686917305;.529411792755
$127;1.;
$ANSA_COLOR;401031;SECTION_SHELL;.556862771511078;0.10196078568697;.462745100259
$781;1.;
$ANSA_COLOR;401032;SECTION_SOLID;.835294127464294;.105882354080677;.450980395078
$659;1.;
$ANSA_COLOR;401041;SECTION_SHELL;.564705908298492;.968627452850342;.380392163991
$928;1.;
$ANSA_COLOR;401042;SECTION_SOLID;.843137264251709;.972549021244049;.368627458810
$806;1.;
$ANSA_COLOR;401051;SECTION_SHELL;.576470613479614;.835294127464294;.298039227724
$075;1.;
$ANSA_COLOR;401052;SECTION_SOLID;.850980401039124;.839215695858002;.286274522542
$953;1.;
$ANSA_COLOR;401061;SECTION_SHELL;.584313750267029;.701960802078247;.219607844948
$769;1.;
$ANSA_COLOR;401062;SECTION_SOLID;.858823537826538;.705882370471954;.207843139767
$647;1.;
$ANSA_COLOR;401071;SECTION_SHELL;.592156887054443;0.5686274766922;.1372549086809
$16;1.;
$ANSA_COLOR;401072;SECTION_SOLID;.866666674613953;.572549045085907;.125490203499
$794;1.;
$ANSA_COLOR;401081;SECTION_SHELL;.600000023841858;0.43529412150383;.058823529630
$899;1.;
$ANSA_COLOR;401082;SECTION_SOLID;.878431379795074;.439215689897537;0.04313725605
$607;1.;
$ANSA_COLOR;401091;SECTION_SHELL;0.61176472902298;0.30588236451149;.976470589637
$756;1.;
$ANSA_COLOR;401092;SECTION_SOLID;.886274516582489;.309803932905197;.964705884456
$635;1.;
$ANSA_COLOR;401101;SECTION_SHELL;.619607865810394;.172549024224281;.894117653369
$904;1.;
$ANSA_COLOR;401102;SECTION_SOLID;.894117653369904;.176470592617989;.882352948188
$782;1.;
$ANSA_COLOR;401111;SECTION_SHELL;.627451002597809;.039215687662363;.815686285495
$758;1.;
$ANSA_COLOR;401112;SECTION_SOLID;.901960790157318;0.04313725605607;.800000011920
$929;1.;
$ANSA_COLOR;401121;SECTION_SHELL;.635294139385223;.905882358551025;.733333349227
$905;1.;
$ANSA_COLOR;401122;SECTION_SOLID;0.91372549533844;.909803926944733;.721568644046
$783;1.;
$ANSA_COLOR;402010;SECTION_BEAM_ELFORM_6;.733333349227905;.317647069692612;.7725
$49033164978;1.;
$ANSA_COLOR;402020;SECTION_BEAM_ELFORM_6;0.74117648601532;.184313729405403;.6901
$96096897125;1.;
$ANSA_COLOR;402030;SECTION_BEAM_ELFORM_6;.749019622802734;.050980392843485;0.611
$76472902298;1.;
$ANSA_COLOR;402040;SECTION_BEAM_ELFORM_6;.756862759590149;.921568632125854;.5294
$11792755127;1.;
$ANSA_COLOR;402050;SECTION_BEAM_ELFORM_6;.764705896377563;.788235306739807;.4470
$58826684952;1.;
$ANSA_COLOR;402060;SECTION_BEAM_ELFORM_6;.776470601558685;0.65490198135376;.3686
$27458810806;1.;
$ANSA_COLOR;402070;SECTION_BEAM_ELFORM_6;0.7843137383461;.521568655967712;.28627
$4522542953;1.;
$ANSA_COLOR;402080;SECTION_BEAM_ELFORM_6;.792156875133514;.388235300779343;0.203
$92157137394;1.;
$ANSA_COLOR;402090;SECTION_BEAM_ELFORM_6;.800000011920929;.254901975393295;.1254
$90203499794;1.;
$ANSA_COLOR;402100;SECTION_BEAM_ELFORM_6;.811764717102051;.121568627655506;0.043
$13725605607;1.;
$ANSA_COLOR;402110;SECTION_BEAM_ELFORM_6;.819607853889465;.988235294818878;.9607
$84316062927;1.;
$ANSA_COLOR;402120;SECTION_BEAM_ELFORM_6;0.82745099067688;.854901969432831;.8823
$52948188782;1.;
$ANSA_COLOR;403013;SECTION_SOLID;.752941191196442;.686274528503418;0.82745099067
$688;1.;
$ANSA_COLOR;403014;SECTION_SHELL;.839215695858002;.356862753629684;.019607843831
$182;1.;
$ANSA_COLOR;403015;SECTION_SHELL;0.91372549533844;.066666670143604;0.52549022436
$142;1.;
$ANSA_COLOR;403023;SECTION_SOLID;.501960813999176;.117647059261799;.772549033164
$978;1.;
$ANSA_COLOR;403024;SECTION_SHELL;.635294139385223;.015686275437474;.200000002980
$232;1.;
$ANSA_COLOR;403025;SECTION_SHELL;.921568632125854;.933333337306976;.443137258291
$245;1.;
$ANSA_COLOR;403033;SECTION_SOLID;.898039221763611;.184313729405403;.890196084976
$196;1.;
$ANSA_COLOR;403034;SECTION_SHELL;.941176474094391;.239215686917305;.807843148708
$344;1.;
$ANSA_COLOR;403035;SECTION_SHELL;.929411768913269;.800000011920929;.364705890417
$099;1.;
$ANSA_COLOR;403043;SECTION_SOLID;.890196084976196;.666666686534882;.980392158031
$464;1.;
$ANSA_COLOR;403044;SECTION_SHELL;.678431391716003;.545098066329956;.050980392843
$485;1.;
$ANSA_COLOR;403045;SECTION_SHELL;.937254905700684;.670588254928589;.282352954149
$246;1.;
$ANSA_COLOR;403053;SECTION_SOLID;.807843148708344;.658823549747467;0.24705882370
$472;1.;
$ANSA_COLOR;403054;SECTION_SHELL;.839215695858002;.360784322023392;.474509805440
$903;1.;
$ANSA_COLOR;403055;SECTION_SHELL;.949019610881805;.537254929542542;.200000002980
$232;1.;
$ANSA_COLOR;403063;SECTION_SOLID;.901960790157318;.125490203499794;.768627464771
$271;1.;
$ANSA_COLOR;403064;SECTION_SHELL;.847058832645416;.980392158031464;.482352942228
$317;1.;
$ANSA_COLOR;403065;SECTION_SHELL;0.95686274766922;.403921574354172;.121568627655
$506;1.;
$ANSA_COLOR;403073;SECTION_SOLID;.760784327983856;.976470589637756;.749019622802
$734;1.;
$ANSA_COLOR;403074;SECTION_SHELL;.886274516582489;.250980406999588;.168627455830
$574;1.;
$ANSA_COLOR;403075;SECTION_SHELL;.964705884456635;.270588248968124;.039215687662
$363;1.;
$ANSA_COLOR;403083;SECTION_SOLID;.705882370471954;.250980406999588;.854901969432
$831;1.;
$ANSA_COLOR;403084;SECTION_SHELL;.752941191196442;.039215687662363;.450980395078
$659;1.;
$ANSA_COLOR;403085;SECTION_SHELL;.972549021244049;.137254908680916;0.95686274766
$922;1.;
$ANSA_COLOR;403093;SECTION_SOLID;0.87058824300766;.850980401039124;.505882382392
$883;1.;
$ANSA_COLOR;403094;SECTION_SHELL;.505882382392883;.482352942228317;0.61176472902
$298;1.;
$ANSA_COLOR;403095;SECTION_SHELL;.984313726425171;.003921568859369;.878431379795
$074;1.;
$ANSA_COLOR;403103;SECTION_SOLID;.749019622802734;.776470601558685;.705882370471
$954;1.;
$ANSA_COLOR;403104;SECTION_SHELL;.643137276172638;.588235318660736;.658823549747
$467;1.;
$ANSA_COLOR;403105;SECTION_SHELL;.992156863212585;0.87058824300766;.796078443527
$222;1.;
$ANSA_COLOR;403113;SECTION_SOLID;.850980401039124;.027450980618596;.454901963472
$366;1.;
$ANSA_COLOR;403114;SECTION_SHELL;.662745118141174;0.34901961684227;.584313750267
$029;1.;
$ANSA_COLOR;403115;SECTION_SHELL;.501960813999176;.737254917621613;.713725507259
$369;1.;
$ANSA_COLOR;403123;SECTION_SOLID;0.87058824300766;.007843137718737;.152941182255
$745;1.;
$ANSA_COLOR;403124;SECTION_SHELL;.772549033164978;.172549024224281;.792156875133
$514;1.;
$ANSA_COLOR;403125;SECTION_SHELL;.509803950786591;.603921592235565;.635294139385
$223;1.;
$ANSA_COLOR;403501;SECTION_SHELL;.533333361148834;.749019622802734;.847058832645
$416;1.;
$ANSA_COLOR;403502;SECTION_SOLID;.945098042488098;.078431375324726;0.65490198135
$376;1.;
$ANSA_COLOR;403503;SECTION_SHELL;.921568632125854;0.26274511218071;.109803922474
$384;1.;
$ANSA_COLOR;403601;SECTION_SHELL;.658823549747467;.047058824449778;.945098042488
$098;1.;
$ANSA_COLOR;403602;SECTION_SOLID;.572549045085907;.376470595598221;.752941191196
$442;1.;
$ANSA_COLOR;403603;SECTION_SHELL;.964705884456635;.160784319043159;.380392163991
$928;1.;
$ANSA_COLOR;403604;SECTION_SHELL;.850980401039124;.254901975393295;.498039215803
$146;1.;
$ANSA_COLOR;404001;SECTION_SOLID;.933333337306976;.862745106220245;.509803950786
$591;1.;
$ANSA_COLOR;404009;SECTION_SHELL;.517647087574005;.639215707778931;.380392163991
$928;1.;
$ANSA_COLOR;404010;SECTION_SHELL;.580392181873322;.482352942228317;.647058844566
$345;1.;
$ANSA_COLOR;404201;SECTION_SOLID;.933333337306976;.862745106220245;.509803950786
$591;1.;
$ANSA_COLOR;404401;SECTION_SOLID;.933333337306976;.862745106220245;.509803950786
$591;1.;
$ANSA_COLOR;404409;SECTION_SHELL;.615686297416687;.090196080505848;.050980392843
$485;1.;
$ANSA_COLOR;404501;SECTION_BEAM_ELFORM_3;.764705896377563;.811764717102051;0.525
$49022436142;1.;
$ANSA_COLOR;404502;SECTION_BEAM_ELFORM_3;.662745118141174;.878431379795074;.6470
$58844566345;1.;
$ANSA_COLOR;404503;SECTION_BEAM_ELFORM_3;.627451002597809;.447058826684952;.7372
$54917621613;1.;
$ANSA_COLOR;404504;SECTION_BEAM_ELFORM_3;.545098066329956;.592156887054443;.0745
$09806931019;1.;
$ANSA_COLOR;404601;SECTION_BEAM_ELFORM_3;.588235318660736;.282352954149246;.1490
$19613862038;1.;
$ANSA_COLOR;404602;SECTION_BEAM_ELFORM_3;.709803938865662;.823529422283173;.8901
$96084976196;1.;
$ANSA_COLOR;404603;SECTION_BEAM_ELFORM_3;0.7843137383461;.949019610881805;0.8705
$8824300766;1.;
$ANSA_COLOR;404604;SECTION_BEAM_ELFORM_3;.815686285495758;.647058844566345;.0980
$39217293262;1.;
$ANSA_COLOR;404605;SECTION_BEAM_ELFORM_3;.803921580314636;.925490200519562;0.568
$6274766922;1.;
$ANSA_COLOR;404606;SECTION_BEAM_ELFORM_3;.745098054409027;.780392169952393;.2823
$52954149246;1.;
$ANSA_COLOR;404607;SECTION_BEAM_ELFORM_3;.643137276172638;.215686276555061;.2431
$37255311012;1.;
$ANSA_COLOR;404608;SECTION_BEAM_ELFORM_3;.498039215803146;.227450981736183;.4470
$58826684952;1.;
$ANSA_COLOR;404609;SECTION_BEAM_ELFORM_3;.807843148708344;.815686285495758;.8941
$17653369904;1.;
$ANSA_COLOR;404610;SECTION_BEAM_ELFORM_3;.572549045085907;.984313726425171;.5882
$35318660736;1.;
$ANSA_COLOR;404611;SECTION_BEAM_ELFORM_3;.792156875133514;.725490212440491;0.525
$49022436142;1.;
$ANSA_COLOR;404612;SECTION_BEAM_ELFORM_3;.968627452850342;.050980392843485;.7058
$82370471954;1.;
$ANSA_COLOR;404702;SECTION_BEAM_ELFORM_3;.933333337306976;.615686297416687;.8000
$00011920929;1.;
$ANSA_COLOR;404703;SECTION_BEAM_ELFORM_3;.686274528503418;.427450984716415;.8039
$21580314636;1.;
$ANSA_COLOR;404704;SECTION_BEAM_ELFORM_3;.898039221763611;.815686285495758;.0509
$80392843485;1.;
$ANSA_COLOR;404705;SECTION_BEAM_ELFORM_3;.560784339904785;0.7843137383461;.54509
$8066329956;1.;
$ANSA_COLOR;404706;SECTION_BEAM_ELFORM_3;.682352960109711;.329411774873734;.2823
$52954149246;1.;
$ANSA_COLOR;404707;SECTION_BEAM_ELFORM_3;.925490200519562;0.7843137383461;.59607
$8455448151;1.;
$ANSA_COLOR;404708;SECTION_BEAM_ELFORM_3;0.95686274766922;.486274510622025;.8235
$29422283173;1.;
$ANSA_COLOR;405001;SECTION_SOLID;.858823537826538;.619607865810394;0.87058824300
$766;1.;
$ANSA_COLOR;405003;SECTION_SHELL;.905882358551025;.439215689897537;.058823529630
$899;0.5;
$ANSA_COLOR;406001;SECTION_SHELL;.545098066329956;.545098066329956;0.47843137383
$461;0.5;
$ANSA_COLOR;406002;SECTION_SOLID;.576470613479614;.439215689897537;.858823537826
$538;0.5;
$ANSA_COLOR;406003;SECTION_SHELL;.968627452850342;.749019622802734;.482352942228
$317;0.5;
$ANSA_COLOR;406013;SECTION_SHELL;.803921580314636;.200000002980232;.200000002980
$232;.699999988079071;
$ANSA_COLOR;453013;SECTION_SOLID;.603921592235565;.894117653369904;.007843137718
$737;1.;
$ANSA_COLOR;453014;SECTION_SHELL;.592156887054443;.168627455830574;0.47843137383
$461;1.;
$ANSA_COLOR;453015;SECTION_SHELL;0.7843137383461;.768627464771271;.4274509847164
$15;1.;
$ANSA_COLOR;453023;SECTION_SOLID;.807843148708344;.180392161011696;.733333349227
$905;1.;
$ANSA_COLOR;453024;SECTION_SHELL;.619607865810394;.772549033164978;.184313729405
$403;1.;
$ANSA_COLOR;453025;SECTION_SHELL;.792156875133514;.635294139385223;.345098048448
$563;1.;
$ANSA_COLOR;453033;SECTION_SOLID;.529411792755127;.560784339904785;.831372559070
$587;1.;
$ANSA_COLOR;453034;SECTION_SHELL;.749019622802734;0.30588236451149;.768627464771
$271;1.;
$ANSA_COLOR;453035;SECTION_SHELL;.803921580314636;.501960813999176;0.26274511218
$071;1.;
$ANSA_COLOR;453043;SECTION_SOLID;.800000011920929;.933333337306976;.141176477074
$623;1.;
$ANSA_COLOR;453044;SECTION_SHELL;.764705896377563;.498039215803146;.235294118523
$598;1.;
$ANSA_COLOR;453045;SECTION_SHELL;.811764717102051;.368627458810806;.184313729405
$403;1.;
$ANSA_COLOR;453053;SECTION_SOLID;.619607865810394;.294117659330368;.670588254928
$589;1.;
$ANSA_COLOR;453054;SECTION_SHELL;.662745118141174;0.34901961684227;.584313750267
$029;1.;
$ANSA_COLOR;453055;SECTION_SHELL;.819607853889465;.235294118523598;0.10196078568
$697;1.;
$ANSA_COLOR;453063;SECTION_SOLID;.639215707778931;.905882358551025;0.52549022436
$142;1.;
$ANSA_COLOR;453064;SECTION_SHELL;.996078431606293;.650980412960052;.411764711141
$586;1.;
$ANSA_COLOR;453065;SECTION_SHELL;0.82745099067688;0.10196078568697;.019607843831
$182;1.;
$ANSA_COLOR;453073;SECTION_SOLID;.807843148708344;.078431375324726;.635294139385
$223;1.;
$ANSA_COLOR;453074;SECTION_SHELL;.921568632125854;0.;.364705890417099;1.;
$ANSA_COLOR;453075;SECTION_SHELL;.839215695858002;.968627452850342;.941176474094
$391;1.;
$ANSA_COLOR;453083;SECTION_SOLID;.862745106220245;.905882358551025;.631372570991
$516;1.;
$ANSA_COLOR;453084;SECTION_SHELL;.898039221763611;.341176480054855;.537254929542
$542;1.;
$ANSA_COLOR;453085;SECTION_SHELL;.847058832645416;.835294127464294;.858823537826
$538;1.;
$ANSA_COLOR;453093;SECTION_SOLID;.803921580314636;.396078437566757;.505882382392
$883;1.;
$ANSA_COLOR;453094;SECTION_SHELL;.929411768913269;.674509823322296;.921568632125
$854;1.;
$ANSA_COLOR;453095;SECTION_SHELL;.854901969432831;.701960802078247;.780392169952
$393;1.;
$ANSA_COLOR;453103;SECTION_SOLID;.631372570991516;.545098066329956;.258823543787
$003;1.;
$ANSA_COLOR;453104;SECTION_SHELL;.509803950786591;0.;.521568655967712;1.;
$ANSA_COLOR;453105;SECTION_SHELL;.862745106220245;0.5686274766922;0.698039233684
$54;1.;
$ANSA_COLOR;453113;SECTION_SOLID;.843137264251709;.352941185235977;.898039221763
$611;1.;
$ANSA_COLOR;453114;SECTION_SHELL;.643137276172638;.321568638086319;.337254911661
$148;1.;
$ANSA_COLOR;453115;SECTION_SHELL;0.87058824300766;0.43529412150383;.615686297416
$687;1.;
$ANSA_COLOR;453123;SECTION_SOLID;.941176474094391;.819607853889465;.415686279535
$294;1.;
$ANSA_COLOR;453124;SECTION_SHELL;.831372559070587;.631372570991516;.368627458810
$806;1.;
$ANSA_COLOR;453125;SECTION_SHELL;.882352948188782;0.30588236451149;.537254929542
$542;1.;
$ANSA_COLOR;453503;SECTION_SHELL;.854901969432831;.623529434204102;.341176480054
$855;1.;
$ANSA_COLOR;453601;SECTION_SHELL;.901960790157318;.447058826684952;.635294139385
$223;1.;
$ANSA_COLOR;453602;SECTION_SOLID;.831372559070587;.945098042488098;.658823549747
$467;1.;
$ANSA_COLOR;453603;SECTION_SHELL;.776470601558685;.533333361148834;.054901961237
$192;1.;
$ANSA_COLOR;453604;SECTION_SHELL;.603921592235565;.066666670143604;.501960813999
$176;1.;
$ANSA_COLOR;454001;SECTION_SOLID;.933333337306976;.862745106220245;.509803950786
$591;1.;
$ANSA_COLOR;454009;SECTION_SHELL;.733333349227905;.235294118523598;0.24705882370
$472;1.;
$ANSA_COLOR;454010;SECTION_SHELL;.858823537826538;.423529416322708;.419607847929
$001;1.;
$ANSA_COLOR;454201;SECTION_SOLID;.933333337306976;.862745106220245;.509803950786
$591;1.;
$ANSA_COLOR;454400;SECTION_SOLID;.933333337306976;.862745106220245;.509803950786
$591;1.;
$ANSA_COLOR;454409;SECTION_SHELL;.627451002597809;.811764717102051;.580392181873
$322;1.;
$ANSA_COLOR;454501;SECTION_BEAM_ELFORM_3;0.82745099067688;.266666680574417;.5294
$11792755127;1.;
$ANSA_COLOR;454502;SECTION_BEAM_ELFORM_3;.945098042488098;.764705896377563;.2941
$17659330368;1.;
$ANSA_COLOR;454503;SECTION_BEAM_ELFORM_3;.909803926944733;.121568627655506;.1921
$56866192818;1.;
$ANSA_COLOR;454504;SECTION_BEAM_ELFORM_3;.941176474094391;.552941203117371;.0980
$39217293262;1.;
$ANSA_COLOR;454601;SECTION_BEAM_ELFORM_3;.749019622802734;.725490212440491;.1568
$62750649452;1.;
$ANSA_COLOR;454602;SECTION_BEAM_ELFORM_3;.905882358551025;.066666670143604;.6431
$37276172638;1.;
$ANSA_COLOR;454603;SECTION_BEAM_ELFORM_3;.521568655967712;.988235294818878;.3725
$49027204514;1.;
$ANSA_COLOR;454604;SECTION_BEAM_ELFORM_3;.721568644046783;.286274522542953;.6745
$09823322296;1.;
$ANSA_COLOR;454605;SECTION_BEAM_ELFORM_3;.952941179275513;.384313732385635;.3019
$60796117783;1.;
$ANSA_COLOR;454606;SECTION_BEAM_ELFORM_3;.933333337306976;.564705908298492;.2509
$80406999588;1.;
$ANSA_COLOR;454607;SECTION_BEAM_ELFORM_3;.878431379795074;.152941182255745;.6470
$58844566345;1.;
$ANSA_COLOR;454608;SECTION_BEAM_ELFORM_3;.780392169952393;.317647069692612;.2862
$74522542953;1.;
$ANSA_COLOR;454609;SECTION_BEAM_ELFORM_3;.639215707778931;.062745101749897;.1725
$49024224281;1.;
$ANSA_COLOR;454610;SECTION_BEAM_ELFORM_3;.588235318660736;.490196079015732;.3450
$98048448563;1.;
$ANSA_COLOR;454611;SECTION_BEAM_ELFORM_3;0.61176472902298;0.5686274766922;.56470
$5908298492;1.;
$ANSA_COLOR;454612;SECTION_BEAM_ELFORM_3;.592156887054443;.223529413342476;.0274
$50980618596;1.;
$ANSA_COLOR;454702;SECTION_BEAM_ELFORM_3;.823529422283173;.164705887436867;.0078
$43137718737;1.;
$ANSA_COLOR;454703;SECTION_BEAM_ELFORM_3;.537254929542542;.286274522542953;.9372
$54905700684;1.;
$ANSA_COLOR;454704;SECTION_BEAM_ELFORM_3;.705882370471954;.988235294818878;.1098
$03922474384;1.;
$ANSA_COLOR;454705;SECTION_BEAM_ELFORM_3;.529411792755127;.454901963472366;.7333
$33349227905;1.;
$ANSA_COLOR;454706;SECTION_BEAM_ELFORM_3;.917647063732147;.266666680574417;.6862
$74528503418;1.;
$ANSA_COLOR;454707;SECTION_BEAM_ELFORM_3;.764705896377563;0.65490198135376;.8823
$52948188782;1.;
$ANSA_COLOR;454708;SECTION_BEAM_ELFORM_3;.564705908298492;.623529434204102;.3215
$68638086319;1.;
$ANSA_COLOR;455001;SECTION_SOLID;.521568655967712;.321568638086319;.513725519180
$298;1.;
$ANSA_COLOR;455003;SECTION_SHELL;.803921580314636;0.;.803921580314636;0.5;
$ANSA_COLOR;456001;SECTION_SHELL;.976470589637756;.003921568859369;.854901969432
$831;1.;
$ANSA_COLOR;456002;SECTION_SOLID;.764705896377563;.725490212440491;.278431385755
$539;1.;
$ANSA_COLOR;456003;SECTION_SHELL;.945098042488098;.301960796117783;.627451002597
$809;0.5;
$ANSA_COLOR;456013;SECTION_SHELL;.513725519180298;.490196079015732;.309803932905
$197;1.;
$ANSA_USER_ATTRIBUTES;SECTION_SHELL;User/cad_material;TEXT;RW;YES;;;
$ANSA_USER_ATTRIBUTES;SECTION_SHELL;User/cad_thickness;TEXT;RW;YES;;;
$ANSA_USER_ATTRIBUTES;SECTION_SOLID;User/cad_material;TEXT;RW;YES;;;
*END
